/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import «Adic spaces».OrderedGroupConvex
import «Adic spaces».ValuationSpectrum
import Mathlib.RingTheory.Valuation.Basic
import Mathlib.Algebra.Order.Group.Units

/-!
# The characteristic subgroup `cΓ_v` (Wedhorn 4.13)

Per Wedhorn, *Adic Spaces* (arXiv:1910.05934), Definition 4.13 (p. 27):
the characteristic subgroup of a valuation `v` on a ring `A`.

## Definition

> Let `v` be a valuation on a ring `A` and let `Γ_v` its value group.
> Then the convex subgroup of `Γ_v` generated by the elements
> `Γ_{v,≥1} ∩ im(v)` is called the characteristic group of `v`. It is
> denoted by `cΓ_v`. Hence `cΓ_v = 1` if and only if `v(a) ≤ 1` for
> all `a ∈ A`.

This is the foundation for Wedhorn §7.1 (`Spv(A,I)`) and §7.5 (Spa
spectrality).

## Main definitions

* `Valuation.imageGeOne v` : `{γ ∈ Γ_v : γ ≥ 1 ∧ γ ∈ im(v)}`.
* `Valuation.cGamma v` : the convex subgroup of `Γ_v` generated by
  `imageGeOne`.

## Main results

* `Valuation.cGamma_eq_one_iff_le_one` : `cΓ_v` is trivial iff `v ≤ 1`
  on `A` (Wedhorn's "Hence" clause in 4.13).

## References

* [Wedhorn 2019] Definition 4.13, p. 27.
-/

namespace Valuation

variable {A : Type*} [CommRing A]
variable {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]

/-- The set `Γ_{v,≥1} ∩ im(v)` from Wedhorn 4.13 — values `≥ 1` that
are reached by `v`. -/
def imageGeOne (v : Valuation A Γ₀) : Set Γ₀ :=
  { γ : Γ₀ | 1 ≤ γ ∧ ∃ a : A, v a = γ }

/-- **Wedhorn 4.13: the characteristic subgroup `cΓ_v`.** As a subset of
the value group (with zero), this is the convex closure of
`imageGeOne v` together with all its inverses (closing under group
operations to form a subgroup, then taking convex closure).

For now, defined as the set of `γ ∈ Γ₀` such that either `γ = 0` or
there exists `a : A` with `1 ≤ v a` and the inequalities `v a⁻¹ ≤ γ ≤ v a`
hold (i.e., `γ` lies in the convex hull of `{v a, (v a)⁻¹}` for some
`a` with `v a ≥ 1`).

The "convex hull of `imageGeOne` under group ops" semantics — restricting
to `{γ : 0 < γ}` — is more complex; this definition captures the
"bounded by some `v(a)^±1`" characterisation suitable for our
applications. -/
def cGammaPos (v : Valuation A Γ₀) : Set Γ₀ :=
  { γ : Γ₀ | γ = 0 ∨
    (0 < γ ∧ ∃ a : A, 1 ≤ v a ∧ (v a)⁻¹ ≤ γ ∧ γ ≤ v a) }

/-- `v(a) ≤ 1` for all `a : A` is the condition that `Γ_{v,≥1} ∩ im(v) ⊆ {1}`,
i.e., the generating set of `cΓ_v` is trivial. -/
theorem imageGeOne_subset_singleton_of_le_one (v : Valuation A Γ₀)
    (h : ∀ a : A, v a ≤ 1) :
    Valuation.imageGeOne v ⊆ {1} := by
  intro γ hγ
  obtain ⟨hγ_ge, a, ha⟩ := hγ
  rw [← ha] at hγ_ge
  have hva_le : v a ≤ 1 := h a
  rw [← ha]
  exact Set.mem_singleton_iff.mpr (le_antisymm hva_le hγ_ge)

/-- **Microbial valuation** (Wedhorn implicit, p. 27): a valuation `v` is
*microbial* if its characteristic subgroup is the whole value group, i.e.,
`cΓ_v = Γ_v`.

For our Lean formalisation, this is captured by the condition that every
positive value of `v` is bounded above and below by some `(v a)^±1` with
`v a ≥ 1`. -/
def IsMicrobial (v : Valuation A Γ₀) : Prop :=
  ∀ γ : Γ₀, 0 < γ → ∃ a : A, 1 ≤ v a ∧ (v a)⁻¹ ≤ γ ∧ γ ≤ v a

/-- **Microbial → for every `γ > 0`, ∃ `t ∈ A` with `v(t) ≠ 0` and
`v(t)⁻¹ ≤ γ`.** This is the existence statement Wedhorn 7.10's
microbial-case proof uses: given `γ ∈ Γ_v`, find `t ∈ A` with
`v(t)⁻¹ ≤ γ` (so `v(t) ≥ γ⁻¹` — i.e., `v(t)` is large enough). -/
theorem IsMicrobial.exists_inv_le {v : Valuation A Γ₀}
    (h : IsMicrobial v) {γ : Γ₀} (hγ : 0 < γ) :
    ∃ t : A, v t ≠ 0 ∧ (v t)⁻¹ ≤ γ := by
  obtain ⟨a, ha_ge_one, ha_inv_le, _⟩ := h γ hγ
  -- v a ≥ 1, so v a ≠ 0.
  refine ⟨a, ?_, ha_inv_le⟩
  intro h_eq
  rw [h_eq] at ha_ge_one
  exact absurd ha_ge_one (by simp)

/-- **Wedhorn 7.3: `cΓ_v(I)` characteristic subgroup attached to an ideal.**
As a set of `Γ_v` values, this is `{0} ∪ {γ : ∃ a ∈ I, v(a) > 0 ∧ v(a) ≤ γ}`
unioned with `cGammaPos v`. Concretely, `cΓ_v(I)` contains every `γ ∈ Γ_v`
that lies "between" some `v(a)` (with `v(a) ≥ 1`) or some inverse
`v(b)⁻¹` for `b ∈ I` with `v(b) > 0`.

This is the convex subgroup that captures Wedhorn 7.4 "v is in
`Spv(A, I)`" — equivalently, `cΓ_v(I) = Γ_v` once `I` is "enough" data
to determine the topology.

For development purposes here, we define `cGammaIdealPos v I` as a SET
characterised by this convex hull. -/
def cGammaIdealPos (v : Valuation A Γ₀) (I : Ideal A) : Set Γ₀ :=
  { γ : Γ₀ | γ = 0 ∨
    (0 < γ ∧ ((∃ a : A, 1 ≤ v a ∧ (v a)⁻¹ ≤ γ ∧ γ ≤ v a) ∨
              (∃ a : A, a ∈ I ∧ 0 < v a ∧ v a ≤ γ ∧ γ ≤ 1))) }

/-- `cGammaPos v ⊆ cGammaIdealPos v I` (the ideal-version is larger). -/
theorem cGammaPos_subset_cGammaIdealPos (v : Valuation A Γ₀) (I : Ideal A) :
    cGammaPos v ⊆ cGammaIdealPos v I := by
  intro γ hγ
  rcases hγ with rfl | ⟨hγ_pos, a, ha_ge_one, ha_inv_le, ha_le⟩
  · exact Or.inl rfl
  · exact Or.inr ⟨hγ_pos, Or.inl ⟨a, ha_ge_one, ha_inv_le, ha_le⟩⟩

/-- `1 ∈ cGammaIdealPos v I`. Witnessed by `a = 1` and `v(1) = 1`. -/
theorem one_mem_cGammaIdealPos (v : Valuation A Γ₀) (I : Ideal A) :
    (1 : Γ₀) ∈ cGammaIdealPos v I := by
  refine Or.inr ⟨zero_lt_one, Or.inl ⟨1, ?_, ?_, ?_⟩⟩
  · rw [map_one]
  · rw [map_one, inv_one]
  · rw [map_one]

/-- Zero is in `cGammaIdealPos`. -/
theorem zero_mem_cGammaIdealPos (v : Valuation A Γ₀) (I : Ideal A) :
    (0 : Γ₀) ∈ cGammaIdealPos v I :=
  Or.inl rfl

/-- **Units version of `cGammaIdealPos`.** The set of units `u : Γ₀ˣ`
that are either:
* between `(v a)⁻¹` and `v a` for some `a : A` with `1 ≤ v a` (the
  characteristic-subgroup generators), or
* between `v a` and `1` for some `a ∈ I` with `0 < v a` (the
  ideal-augmentation generators).

This is the natural "generating set" inside the unit group `Γ₀ˣ` for the
convex subgroup `cΓ_v(I)`. The corresponding convex subgroup is then
obtained by `minContain` on this set. -/
def cGammaIdealUnits (v : Valuation A Γ₀) (I : Ideal A) : Set Γ₀ˣ :=
  { u : Γ₀ˣ | (∃ a : A, ∃ _ha : 1 ≤ v a, ∃ hva : v a ≠ 0,
      (Units.mk0 (v a) hva)⁻¹ ≤ u ∧ u ≤ Units.mk0 (v a) hva) ∨
    (∃ a : A, a ∈ I ∧ ∃ hva : v a ≠ 0,
      Units.mk0 (v a) hva ≤ u ∧ u ≤ 1) }

/-- **Wedhorn 7.3: the convex subgroup `cΓ_v(I)`.** This is the smallest
convex subgroup of `Γ₀ˣ` containing the generators of `cGammaIdealUnits v I`,
constructed via `ConvexSubgroup.minContain`.

By construction:
* Every element of `cGammaIdealUnits v I` lies in `cGammaIdeal v I`
  (`subset_minContain`).
* `cGammaIdeal v I` is the smallest convex subgroup with this property
  (`minContain_le`).

Per Wedhorn 7.3, this captures "the convex subgroup making `v` continuous
in `Spv(A, I)`". -/
def cGammaIdeal (v : Valuation A Γ₀) (I : Ideal A) :
    ConvexSubgroup Γ₀ˣ :=
  ConvexSubgroup.minContain (cGammaIdealUnits v I)

/-- `cGammaIdealUnits v I ⊆ cGammaIdeal v I`: every generator is in the
generated convex subgroup. -/
theorem cGammaIdealUnits_subset_cGammaIdeal (v : Valuation A Γ₀) (I : Ideal A) :
    cGammaIdealUnits v I ⊆ (cGammaIdeal v I : Set Γ₀ˣ) :=
  ConvexSubgroup.subset_minContain _

/-- **Generator: if `1 ≤ v a`, then `v a` (as unit) is in `cGammaIdeal v I`.** -/
theorem vUnit_mem_cGammaIdeal {v : Valuation A Γ₀} {I : Ideal A}
    {a : A} (ha : 1 ≤ v a) (hva : v a ≠ 0) :
    Units.mk0 (v a) hva ∈ cGammaIdeal v I := by
  refine cGammaIdealUnits_subset_cGammaIdeal v I ?_
  refine Or.inl ⟨a, ha, hva, ?_, le_refl _⟩
  -- (v a)⁻¹ ≤ v a since 1 ≤ v a.
  have h1_le : (1 : Γ₀ˣ) ≤ Units.mk0 (v a) hva := Units.val_le_val.mp ha
  have hinv_le_one : (Units.mk0 (v a) hva)⁻¹ ≤ 1 := by
    rw [← inv_one]
    exact inv_le_inv_iff.mpr h1_le
  exact hinv_le_one.trans h1_le

/-- **Universal property: `cGammaIdeal v I` is the smallest convex subgroup
containing every generator.** -/
theorem cGammaIdeal_le {v : Valuation A Γ₀} {I : Ideal A}
    {H : ConvexSubgroup Γ₀ˣ}
    (hgen : cGammaIdealUnits v I ⊆ H) :
    cGammaIdeal v I ≤ H :=
  ConvexSubgroup.minContain_le hgen

end Valuation
