/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import «Adic spaces».LaurentRefinement
import «Adic spaces».PresheafTateStructure
import «Adic spaces».TopologyComparison

/-!
# Iterated Rational Localization (Wedhorn Lemma 2.13)

For a rational datum `D₀ : RationalLocData A` on a strongly noetherian Tate
ring `A`, and for iterated data (`laurent±Datum D₀ f` for `f : A`), the
iterated rational localization `presheafValue (laurent±Datum D₀ f)` is
isomorphic to a single rational localization of `B := presheafValue D₀`.

This module houses the proofs of:
- `presheafValue_iteratedMinus_equiv` (minus branch, Q3-STEP2C).
- `presheafValue_iteratedPlus_equiv` (plus branch, Q3-STEP2C).
- `presheafValue_trivialPlus_fSubX_equiv` (Q3-STEP2D, non-discrete f−X
  quotient over generic B).

## References
* [T. Wedhorn, *Adic Spaces*][wedhorn2019adic], Lemma 2.13, Prop 8.7.
-/

namespace ValuationSpectrum

open UniformSpace

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
  [PlusSubring A] [IsHuberRing A] [HasLocLiftPowerBounded A]

/-! ### Helpers -/

section Helpers

variable [IsTateRing A] [IsNoetherianRing A] [T2Space A] [NonarchimedeanRing A]

/-- `D₀.canonicalMap D₀.s` is a unit in `presheafValue D₀`, because `D₀.s`
becomes a unit under `algebraMap A (Localization.Away D₀.s)` (definition of
localization) and `D₀.coeRingHom` preserves units. -/
theorem canonicalMap_s_isUnit (D₀ : RationalLocData A) :
    IsUnit (D₀.canonicalMap D₀.s) := by
  unfold RationalLocData.canonicalMap
  simp only [RingHom.coe_comp, Function.comp_apply]
  exact RingHom.isUnit_map D₀.coeRingHom
    (IsLocalization.Away.algebraMap_isUnit D₀.s)

end Helpers

/-! ### Forward uncompleted ring hom for `presheafValue_iteratedMinus_equiv` -/

section IteratedMinusForward

variable [IsTateRing A] [IsNoetherianRing A] [T2Space A] [NonarchimedeanRing A]

/-- Composite `A → presheafValue D₀ → Localization.Away (canonicalMap f)`. -/
noncomputable def iteratedMinus_baseHom (D₀ : RationalLocData A) (f : A) :
    A →+* Localization.Away (D₀.canonicalMap f) :=
  (algebraMap (presheafValue D₀) (Localization.Away (D₀.canonicalMap f))).comp
    D₀.canonicalMap

/-- `D₀.s * f` becomes a unit in `Localization.Away (canonicalMap f)` via the
base hom: `D₀.s` maps to a unit (since `canonicalMap D₀.s` is a unit in
`presheafValue D₀`, preserved by `algebraMap`) and `f` maps to a unit (since
`canonicalMap f` is the localization element). -/
theorem iteratedMinus_D₀s_mul_f_isUnit (D₀ : RationalLocData A) (f : A) :
    IsUnit (iteratedMinus_baseHom D₀ f (D₀.s * f)) := by
  show IsUnit (algebraMap (presheafValue D₀) _ (D₀.canonicalMap (D₀.s * f)))
  rw [map_mul, map_mul]
  exact ((canonicalMap_s_isUnit D₀).map _).mul
    (IsLocalization.Away.algebraMap_isUnit (D₀.canonicalMap f))

/-- Forward ring hom `Localization.Away (D₀.s * f) → Localization.Away (canonicalMap f)`
(at the uncompleted localization level), obtained by the universal property of
`IsLocalization.Away` using that `D₀.s * f` becomes a unit in the target. -/
noncomputable def iteratedMinus_forwardLocHom (D₀ : RationalLocData A) (f : A) :
    Localization.Away (D₀.s * f) →+* Localization.Away (D₀.canonicalMap f) :=
  IsLocalization.Away.lift (D₀.s * f) (iteratedMinus_D₀s_mul_f_isUnit D₀ f)

/-- The forward localization hom composed with `algebraMap A` equals `iteratedMinus_baseHom`. -/
theorem iteratedMinus_forwardLocHom_algebraMap (D₀ : RationalLocData A) (f : A) (a : A) :
    iteratedMinus_forwardLocHom D₀ f
      (algebraMap A (Localization.Away (D₀.s * f)) a) =
      iteratedMinus_baseHom D₀ f a :=
  IsLocalization.Away.lift_eq (D₀.s * f) (iteratedMinus_D₀s_mul_f_isUnit D₀ f) a

/-- Forward ring hom to the completion: composes `iteratedMinus_forwardLocHom`
with the completion's `coeRingHom`. -/
noncomputable def iteratedMinus_forwardToCompletion
    (P : PairOfDefinition A) [IsNoetherianRing P.A₀]
    (D₀ : RationalLocData A) [IsNoetherianRing (locSubring D₀.P D₀.T D₀.s)]
    (f : A) :
    Localization.Away ((laurentMinusDatum D₀ f).s) →+*
      presheafValue (iteratedMinusDatum_B P D₀ f) :=
  (iteratedMinusDatum_B P D₀ f).coeRingHom.comp
    (iteratedMinus_forwardLocHom D₀ f)

/-- Continuity of `iteratedMinus_forwardToCompletion` wrt the laurentMinus
topology on the source and the completion uniformity on the target.

**Proof content (deferred):** The source topology is the localization topology
on `Localization.Away (D₀.s · f)` generated by `locBasis D₀.P (laurentMinusDatum D₀ f).T (D₀.s · f) hopen`.
The target topology is the completion uniformity of `iteratedMinusDatum_B`,
which is the localization topology on `Localization.Away (canonicalMap f)` over
`presheafValue D₀`. Under the canonical map `A → presheafValue D₀` (which is
continuous as a completion map), bounded sets map to bounded sets, so basic
neighborhoods of 0 in the source map into basic neighborhoods of 0 in the target.

This proof requires careful bookkeeping of the two locBasis structures and
the base-change behaviour; ~60 lines. Deferred pending full Q3-STEP2C execution. -/
theorem iteratedMinus_forwardToCompletion_continuous
    (P : PairOfDefinition A) [IsNoetherianRing P.A₀]
    (D₀ : RationalLocData A) [IsNoetherianRing (locSubring D₀.P D₀.T D₀.s)]
    (f : A) :
    @Continuous _ _ (laurentMinusDatum D₀ f).topology _
      (iteratedMinus_forwardToCompletion P D₀ f) := by
  sorry

/-- Forward RingHom between the two completions — extension via
`UniformSpace.Completion.extensionHom`. -/
noncomputable def iteratedMinus_forwardHom
    (P : PairOfDefinition A) [IsNoetherianRing P.A₀]
    (D₀ : RationalLocData A) [IsNoetherianRing (locSubring D₀.P D₀.T D₀.s)]
    (f : A) :
    presheafValue (laurentMinusDatum D₀ f) →+*
      presheafValue (iteratedMinusDatum_B P D₀ f) := by
  letI : UniformSpace (Localization.Away (laurentMinusDatum D₀ f).s) :=
    (laurentMinusDatum D₀ f).uniformSpace
  letI : IsUniformAddGroup (Localization.Away (laurentMinusDatum D₀ f).s) :=
    (laurentMinusDatum D₀ f).isUniformAddGroup
  letI : IsTopologicalRing (Localization.Away (laurentMinusDatum D₀ f).s) :=
    (laurentMinusDatum D₀ f).isTopologicalRing
  exact UniformSpace.Completion.extensionHom
    (iteratedMinus_forwardToCompletion P D₀ f)
    (iteratedMinus_forwardToCompletion_continuous P D₀ f)

end IteratedMinusForward

/-! ### Backward uncompleted ring hom for `presheafValue_iteratedMinus_equiv`

The backward direction goes from `presheafValue (iteratedMinusDatum_B P D₀ f)`
(completion of `Loc_B(canonicalMap f)`) back to `presheafValue (laurentMinusDatum D₀ f)`.

Key observation: in `presheafValue (laurentMinusDatum D₀ f)`, the element
`D₀.s · f` is a unit (localization), hence `f` is a unit too (since `D₀.s`
is a unit — follows from it being in the ring and the product being a unit).
So `canonicalMap f` becomes a unit in the LHS completion, and by the universal
property of `Localization.Away (canonicalMap f)`, we get a RingHom back. -/

section IteratedMinusBackward

variable [IsTateRing A] [IsNoetherianRing A] [T2Space A] [NonarchimedeanRing A]

/-- In `Localization.Away (D₀.s * f)`, the element `algebraMap f` is a unit
(because `D₀.s * f` is a unit and `D₀.s` is also a unit, by the factorisation
argument using `isUnit_of_mul_isUnit_right`). -/
theorem algebraMap_f_isUnit_in_laurentMinus (D₀ : RationalLocData A) (f : A) :
    IsUnit (algebraMap A (Localization.Away (D₀.s * f)) f) := by
  have hmul : algebraMap A (Localization.Away (D₀.s * f)) (D₀.s * f) =
      algebraMap A _ D₀.s * algebraMap A _ f := map_mul _ _ _
  have hu : IsUnit (algebraMap A (Localization.Away (D₀.s * f)) (D₀.s * f)) :=
    IsLocalization.Away.algebraMap_isUnit _
  rw [hmul] at hu
  exact isUnit_of_mul_isUnit_right hu

/-- In `presheafValue (laurentMinusDatum D₀ f)`, the canonical image of `f`
is a unit. This uses that `f` is already a unit in `Localization.Away (D₀.s · f)`
and `coeRingHom` preserves units. -/
theorem canonicalMap_f_isUnit_in_laurentMinus (D₀ : RationalLocData A) (f : A) :
    IsUnit ((laurentMinusDatum D₀ f).canonicalMap f) := by
  unfold RationalLocData.canonicalMap
  simp only [RingHom.coe_comp, Function.comp_apply]
  exact RingHom.isUnit_map _ (algebraMap_f_isUnit_in_laurentMinus D₀ f)

/-- Compatibility: `restrictionMapHom D₀ D' hsub ∘ D₀.canonicalMap = D'.canonicalMap`.
Follows directly from `UniformSpace.Completion.extensionHom_coe` + the
`IsLocalization.Away.lift_eq` identity for the underlying alg map. -/
theorem restrictionMapHom_canonicalMap (D₀ D' : RationalLocData A)
    (h : rationalOpen D'.T D'.s ⊆ rationalOpen D₀.T D₀.s) (a : A) :
    restrictionMapHom D₀ D' h (D₀.canonicalMap a) = D'.canonicalMap a := by
  unfold restrictionMapHom RationalLocData.canonicalMap
  letI := D₀.uniformSpace
  letI := D₀.isTopologicalRing
  letI := D₀.isUniformAddGroup
  letI := D'.uniformSpace
  letI := D'.isTopologicalRing
  letI := D'.isUniformAddGroup
  simp only [RingHom.coe_comp, Function.comp_apply]
  erw [UniformSpace.Completion.extensionHom_coe (restrictionMapAlg D₀ D' h)
    (restrictionMapAlg_continuous D₀ D' h)]
  simp only [restrictionMapAlg, IsLocalization.Away.lift_eq]
  rfl

/-- In `presheafValue (laurentMinusDatum D₀ f)`, the image of `D₀.canonicalMap f`
under the restriction map equals `(laurentMinusDatum D₀ f).canonicalMap f`, which
is a unit. -/
theorem restrictionMap_canonicalMap_f_isUnit
    (D₀ : RationalLocData A) (f : A)
    (hsub : rationalOpen (laurentMinusDatum D₀ f).T (laurentMinusDatum D₀ f).s ⊆
      rationalOpen D₀.T D₀.s) :
    IsUnit (restrictionMapHom D₀ (laurentMinusDatum D₀ f) hsub (D₀.canonicalMap f)) := by
  rw [restrictionMapHom_canonicalMap]
  exact canonicalMap_f_isUnit_in_laurentMinus D₀ f

end IteratedMinusBackward

end ValuationSpectrum
