/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import «Adic spaces».HuberRings
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.Topology.Algebra.Nonarchimedean.Bases

/-!
# Localization Topology for Huber Rings

We construct the non-archimedean ring topology on the localization `A(T/s) = Aₛ`
attached to a rational subset `R(T/s)` of the adic spectrum, following §8.1 of
[Wedhorn, *Adic Spaces*].

Given a pair of definition `(A₀, I)` for a Huber ring `A`, an element `s ∈ A`,
and a finite subset `T ⊆ A`, the localization `Aₛ = Localization.Away s` carries
a canonical ring topology making it into a Huber ring. The construction is:

1. **Ring of definition**: `D = A₀[t₁/s, …, tₙ/s]`, the subring of `Aₛ` generated
   by the image of `A₀` and the fractions `{t/s | t ∈ T}`.
2. **Ideal of definition**: `J = I · D`, the ideal of `D` generated by the image
   of `I` under `A₀ → D`.
3. **Topology**: The images of `Jⁿ` in `Aₛ` form a `RingSubgroupsBasis`, yielding
   a non-archimedean ring topology on `Aₛ`.

## Main definitions

* `Spv.divByS t s` : The element `t/s` in `Localization.Away s`.
* `Spv.locSubring P T s` : The ring of definition `D = A₀[t₁/s, …, tₙ/s]`.
* `Spv.locIdeal P T s` : The ideal of definition `J = I · D` in `D`.
* `Spv.locNhd P T s n` : The `n`-th neighborhood `image(Jⁿ)` in `Aₛ`.
* `Spv.locBasis P T s` : The `RingSubgroupsBasis` structure.
* `Spv.locTopology P T s` : The resulting topology on `Aₛ`.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn2019adic], §8.1
-/

open PairOfDefinition Pointwise

namespace Spv

variable {A : Type*} [CommRing A] [TopologicalSpace A]

/-! ### The ring of definition `D` -/

/-- The element `t/s` in `Localization.Away s`. -/
noncomputable def divByS (t s : A) : Localization.Away s :=
  IsLocalization.mk' (Localization.Away s) t
    (⟨s, ⟨1, pow_one s⟩⟩ : Submonoid.powers s)

omit [TopologicalSpace A] in
/-- When `s = 1`, the fraction `t/1` equals `algebraMap t`. -/
theorem divByS_eq_algebraMap (t : A) :
    divByS t (1 : A) = algebraMap A (Localization.Away (1 : A)) t := by
  unfold divByS
  have : (⟨1, ⟨1, pow_one (1 : A)⟩⟩ : Submonoid.powers (1 : A)) = 1 :=
    Subtype.ext rfl
  rw [this, IsLocalization.mk'_one (M := Submonoid.powers (1 : A))
    (S := Localization.Away (1 : A))]

/-- The subring `D = A₀[t₁/s, …, tₙ/s]` of `Localization.Away s`.
This is the ring of definition for the localization topology on `A(T/s)`.
It is generated by the image of `A₀` under `algebraMap` and the
elements `{t/s | t ∈ T}` (§8.1 of Wedhorn). -/
noncomputable def locSubring (P : PairOfDefinition A) (T : Finset A)
    (s : A) : Subring (Localization.Away s) :=
  Subring.closure
    ((algebraMap A (Localization.Away s)) '' (P.A₀ : Set A) ∪
     Set.range (fun t : T => divByS (t : A) s))

/-- The image of `A₀` under `algebraMap` is contained in `D`. -/
theorem algebraMap_A₀_subset_locSubring (P : PairOfDefinition A)
    (T : Finset A) (s : A) :
    (algebraMap A (Localization.Away s)) '' (P.A₀ : Set A) ⊆
      (locSubring P T s : Set (Localization.Away s)) :=
  Set.subset_union_left.trans Subring.subset_closure

/-- Each element `t/s` (for `t ∈ T`) belongs to `D`. -/
theorem divByS_mem_locSubring (P : PairOfDefinition A)
    (T : Finset A) (s : A) {t : A} (ht : t ∈ T) :
    divByS t s ∈ locSubring P T s :=
  Subring.subset_closure (Set.mem_union_right _ ⟨⟨t, ht⟩, rfl⟩)

/-- The image of `algebraMap A (Localization.Away s)` is contained in `D`
when the source element lies in `A₀`. -/
theorem algebraMap_mem_locSubring (P : PairOfDefinition A)
    (T : Finset A) (s : A) {a : A} (ha : a ∈ P.A₀) :
    algebraMap A (Localization.Away s) a ∈ locSubring P T s :=
  algebraMap_A₀_subset_locSubring P T s ⟨a, ha, rfl⟩

/-! ### The ideal of definition `J` -/

/-- The ring homomorphism `A₀ →+* D` induced by `algebraMap A (Localization.Away s)`,
restricted to have codomain `D = locSubring P T s`. -/
noncomputable def algebraMapD (P : PairOfDefinition A) (T : Finset A)
    (s : A) : P.A₀ →+* (locSubring P T s) :=
  ((algebraMap A (Localization.Away s)).comp P.A₀.subtype).codRestrict
    (locSubring P T s)
    (fun a => algebraMap_A₀_subset_locSubring P T s
      ⟨a, a.property, rfl⟩)

/-- The ideal of definition `J = I · D` in `D`, i.e., the ideal of `D` generated
by the image of `I` under the map `A₀ → D`. -/
noncomputable def locIdeal (P : PairOfDefinition A) (T : Finset A)
    (s : A) : Ideal (locSubring P T s) :=
  Ideal.map (algebraMapD P T s) P.I

/-- The ideal of definition `J` is finitely generated
(since `I` is finitely generated). -/
theorem locIdeal_fg (P : PairOfDefinition A) (T : Finset A) (s : A) :
    (locIdeal P T s).FG :=
  P.fg.map _

/-! ### The neighborhood basis -/

/-- The `n`-th neighborhood of `0` in `Localization.Away s`: the image of `Jⁿ`
under the inclusion `D ↪ Aₛ`, as an additive subgroup of `Aₛ`. -/
noncomputable def locNhd (P : PairOfDefinition A) (T : Finset A) (s : A)
    (n : ℕ) : AddSubgroup (Localization.Away s) :=
  ((locIdeal P T s) ^ n).toAddSubgroup.map
    (locSubring P T s).subtype.toAddMonoidHom

/-- The neighborhoods are antitone: `m ≤ n → locNhd n ≤ locNhd m`. -/
theorem locNhd_antitone (P : PairOfDefinition A) (T : Finset A) (s : A) :
    Antitone (locNhd P T s) :=
  fun _ _ h => AddSubgroup.map_mono
    (Submodule.toAddSubgroup_mono (Ideal.pow_le_pow_right h))

/-- `0 ∈ locNhd n` for all `n`. -/
theorem zero_mem_locNhd (P : PairOfDefinition A) (T : Finset A) (s : A)
    (n : ℕ) : (0 : Localization.Away s) ∈ locNhd P T s n :=
  ⟨0, (locIdeal P T s ^ n).zero_mem, map_zero _⟩

/-! ### The `RingSubgroupsBasis` -/

section Basis

variable [IsTopologicalRing A]

omit [IsTopologicalRing A] in
private theorem locNhd_mul (P : PairOfDefinition A) (T : Finset A)
    (s : A) (i : ℕ) :
    ∃ j, (locNhd P T s j : Set (Localization.Away s)) *
      (locNhd P T s j : Set (Localization.Away s)) ⊆
        (locNhd P T s i : Set (Localization.Away s)) := by
  refine ⟨i, ?_⟩
  rintro _ ⟨_, ⟨d₁, hd₁, rfl⟩, _, ⟨d₂, hd₂, rfl⟩, rfl⟩
  exact ⟨d₁ * d₂, Ideal.pow_le_pow_right (Nat.le_add_left i i)
    (pow_add (locIdeal P T s) i i ▸ Ideal.mul_mem_mul hd₁ hd₂),
    MulMemClass.coe_mul ..⟩

/-- **Left multiplication continuity** for the localization topology (Wedhorn §5.51, §8.1).

For each `x ∈ Aₛ` and `i`, there exists `j` with `x · image(Jʲ) ⊆ image(Jⁱ)`.
This is the core axiom that makes the localization topology a ring topology.

The hypothesis `hopen` encodes the key condition from the rational subset
definition: high powers of `I` can absorb the denominator `s`, i.e., for
large enough `N`, the fraction `b/s` lies in the ring of definition `D`
whenever `b ∈ Iᴺ`. The proof proceeds by decomposing `x = (a/sᵏ)` via
`Localization.induction_on` and handling `algebraMap(a)` (by continuity of
left multiplication in `A`) and `1/s` (by the `hopen` condition) separately,
then composing the two steps by induction on `k`. -/
theorem locNhd_leftMul (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s)
    (x : Localization.Away s) (i : ℕ) :
    ∃ j, (locNhd P T s j : Set (Localization.Away s)) ⊆
      (x * ·) ⁻¹' (locNhd P T s i : Set (Localization.Away s)) := by
  obtain ⟨N, hN⟩ := hopen
  -- Helper 1: `divByS 1 s * ↑d ∈ D` for `d ∈ J^N` (span induction on `J^N`)
  have invS_mem : ∀ {d : locSubring P T s} (_ : d ∈ locIdeal P T s ^ N),
      divByS 1 s * ↑d ∈ locSubring P T s := by
    intro d hd
    rw [locIdeal, ← Ideal.map_pow, ← Ideal.span_eq (P.I ^ N), Ideal.map_span] at hd
    refine Submodule.span_induction (p := fun d _ => divByS 1 s * ↑d ∈ locSubring P T s)
      ?_ ?_ ?_ ?_ hd
    · rintro d ⟨b, hb, rfl⟩
      change divByS 1 s * algebraMap A _ ↑b ∈ _
      rw [show divByS 1 s * algebraMap A (Localization.Away s) ↑b = divByS (↑b) s from by
        unfold divByS
        rw [← IsLocalization.mk'_one (M := Submonoid.powers s) (S := Localization.Away s)
          (↑b : A), ← IsLocalization.mk'_mul, one_mul, mul_one]]
      exact hN b hb
    · simp [(locSubring P T s).zero_mem]
    · intro d1 d2 _ _ h1 h2
      rw [show (↑(d1 + d2) : Localization.Away s) = ↑d1 + ↑d2 from AddMemClass.coe_add ..]
      rw [mul_add]; exact (locSubring P T s).add_mem h1 h2
    · intro r d1 _ h1
      rw [show (↑(r • d1) : Localization.Away s) = ↑r * ↑d1 from MulMemClass.coe_mul ..]
      rw [show divByS 1 s * (↑r * ↑d1) = ↑r * (divByS 1 s * ↑d1) from by ring]
      exact (locSubring P T s).mul_mem r.property h1
  -- Helper 2: `divByS 1 s * locNhd(n+N) ⊆ locNhd(n)` (mul_induction on `J^N * J^n`)
  have invS_step : ∀ (n : ℕ) (y : Localization.Away s),
      y ∈ locNhd P T s (n + N) → divByS 1 s * y ∈ locNhd P T s n := by
    rintro n _ ⟨d, hd, rfl⟩
    change divByS 1 s * ↑d ∈ locNhd P T s n
    rw [show n + N = N + n from Nat.add_comm n N, pow_add] at hd
    refine Submodule.mul_induction_on hd ?_ ?_
    · intro a ha b hb
      change divByS 1 s * (↑a * ↑b) ∈ locNhd P T s n
      rw [show divByS 1 s * (↑a * ↑b) = divByS 1 s * ↑a * ↑b from by ring]
      exact ⟨⟨divByS 1 s * ↑a, invS_mem ha⟩ * b, Ideal.mul_mem_left _ _ hb,
        MulMemClass.coe_mul ..⟩
    · intro y1 y2 h1 h2
      change divByS 1 s * (↑y1 + ↑y2) ∈ locNhd P T s n
      rw [mul_add]; exact (locNhd P T s n).add_mem h1 h2
  -- Helper 3: `algebraMap(a) * locNhd(m₀) ⊆ locNhd(i)` (span induction + continuity)
  have algMap_step : ∀ (a : A), ∃ j, ∀ y ∈ locNhd P T s j,
      algebraMap A (Localization.Away s) a * y ∈ locNhd P T s i := by
    intro a
    obtain ⟨m₀, -, hm₀⟩ := P.hasBasis_nhds_zero.mem_iff.mp
      (continuous_const_mul a |>.continuousAt.preimage_mem_nhds
        (by rw [mul_zero]; exact P.hasBasis_nhds_zero.mem_of_mem trivial (i := i)))
    refine ⟨m₀, ?_⟩
    rintro y ⟨d, hd, rfl⟩
    change algebraMap A (Localization.Away s) a * ↑d ∈ locNhd P T s i
    rw [locIdeal, ← Ideal.map_pow, ← Ideal.span_eq (P.I ^ m₀), Ideal.map_span] at hd
    refine Submodule.span_induction (p := fun d _ =>
      algebraMap A (Localization.Away s) a * ↑d ∈ locNhd P T s i) ?_ ?_ ?_ ?_ hd
    · rintro d ⟨b, hb, rfl⟩
      obtain ⟨c, hc, hval⟩ := hm₀ ⟨b, hb, rfl⟩
      change algebraMap A _ a * algebraMap A _ ↑b ∈ _
      rw [← map_mul, show a * (↑b : A) = ↑c from hval.symm]
      exact ⟨algebraMapD P T s c,
        by rw [locIdeal, ← Ideal.map_pow]; exact Ideal.mem_map_of_mem _ hc, rfl⟩
    · simp [(locNhd P T s i).zero_mem]
    · intro d1 d2 _ _ h1 h2
      rw [show (↑(d1 + d2) : Localization.Away s) = ↑d1 + ↑d2 from AddMemClass.coe_add ..]
      rw [mul_add]; exact (locNhd P T s i).add_mem h1 h2
    · intro r d1 _ h1
      rw [show (↑(r • d1) : Localization.Away s) = ↑r * ↑d1 from MulMemClass.coe_mul ..]
      rw [show algebraMap A (Localization.Away s) a * (↑r * ↑d1) =
        ↑r * (algebraMap A (Localization.Away s) a * ↑d1) from by ring]
      obtain ⟨e, he, he_eq⟩ := h1
      exact ⟨r * e, Ideal.mul_mem_left _ r he,
        congrArg ((↑r : Localization.Away s) * ·) he_eq⟩
  -- Main: decompose `x = mk a ⟨s^k, _⟩` and combine by induction on `k`
  induction x using Localization.induction_on with
  | H p =>
    obtain ⟨a, ⟨_, k, rfl⟩⟩ := p
    induction k generalizing a with
    | zero =>
      simp only [pow_zero]
      obtain ⟨j, hj⟩ := algMap_step a
      exact ⟨j, fun _ hy => hj _ hy⟩
    | succ k ih =>
      have hk1 : s ^ (k + 1) ∈ Submonoid.powers s := ⟨k + 1, rfl⟩
      have hk : s ^ k ∈ Submonoid.powers s := ⟨k, rfl⟩
      have hdecomp : Localization.mk a ⟨s ^ (k + 1), hk1⟩ =
          Localization.mk a ⟨s ^ k, hk⟩ * divByS 1 s := by
        rw [divByS, ← Localization.mk_eq_mk', Localization.mk_mul, mul_one]
        congr 1; exact Subtype.ext (pow_succ s k)
      obtain ⟨j₁, hj₁⟩ := ih a
      refine ⟨j₁ + N, fun y hy => ?_⟩
      simp only [Set.mem_preimage]
      rw [hdecomp, mul_assoc]
      exact hj₁ (invS_step j₁ _ hy)

/-- The `RingSubgroupsBasis` for the localization topology on `Aₛ`.
The neighborhoods `{image(Jⁿ)}` satisfy the axioms for a ring subgroups basis. -/
noncomputable def locBasis (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s) :
    RingSubgroupsBasis (locNhd P T s) :=
  .of_comm _
    (fun i j => ⟨max i j,
      le_inf (locNhd_antitone P T s (le_max_left i j))
        (locNhd_antitone P T s (le_max_right i j))⟩)
    (locNhd_mul P T s)
    (locNhd_leftMul P T s hopen)

/-- The localization topology on `Localization.Away s`, making `D` into an open
subring with the `J`-adic subspace topology.

The neighborhoods of `0` have basis `{image(Jⁿ) | n ∈ ℕ}`, where
`J = locIdeal P T s` is the ideal of definition in `D = locSubring P T s`. -/
noncomputable def locTopology (P : PairOfDefinition A) (T : Finset A)
    (s : A) (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s) :
    TopologicalSpace (Localization.Away s) :=
  (locBasis P T s hopen).topology

end Basis

/-! ### The `hopen` condition for `s = 1` -/

/-- The `hopen` condition holds trivially when `s = 1`: every element `b/1` of the
localization is just `algebraMap b`, which lies in `D` whenever `b ∈ A₀`. -/
theorem hopen_away_one (P : PairOfDefinition A) (T : Finset A) :
    ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) (1 : A) ∈ locSubring P T (1 : A) :=
  ⟨0, fun b _ => by rw [divByS_eq_algebraMap]; exact algebraMap_mem_locSubring P T 1 b.2⟩

/-! ### Remark 8.3 infrastructure: `D = A₀` when `s = 1`, `T = {1}` -/

/-- When `T = {1}` and `s = 1`, the ring of definition `D = A₀[1/1]` equals the image
of `A₀` under `algebraMap`: `D = Subring.map (algebraMap A Aₛ) A₀`.

This holds because the extra generator `1/1 = algebraMap 1` already lies in the image
of `A₀`, so the closure of the union is just the closure of `algebraMap '' A₀`, which
is `A₀.map algebraMap` (since the image of a subring is already a subring). -/
theorem locSubring_singleton_one (P : PairOfDefinition A) :
    locSubring P {1} (1 : A) =
      P.A₀.map (algebraMap A (Localization.Away (1 : A))) := by
  unfold locSubring
  have h_range : Set.range (fun t : ({1} : Finset A) =>
      divByS (↑t : A) (1 : A)) ⊆
      (algebraMap A (Localization.Away (1 : A))) '' (P.A₀ : Set A) := by
    rintro _ ⟨⟨t, ht⟩, rfl⟩
    simp only [Finset.mem_singleton] at ht; subst ht
    exact ⟨1, P.A₀.one_mem, (divByS_eq_algebraMap (1 : A)).symm ▸ rfl⟩
  rw [Set.union_eq_left.mpr h_range, ← Subring.coe_map]
  exact Subring.closure_eq _

/-- `algebraMapD` is surjective when `T = {1}` and `s = 1`, since in that case
`D = A₀.map algebraMap` and every element of `D` is in the image of `A₀`. -/
theorem algebraMapD_surjective_one (P : PairOfDefinition A) :
    Function.Surjective (algebraMapD P {1} (1 : A)) := by
  intro ⟨x, hx⟩
  rw [locSubring_singleton_one] at hx
  obtain ⟨a, ha, rfl⟩ := hx
  exact ⟨⟨a, ha⟩, Subtype.ext rfl⟩

section Remark83Topology

variable [IsTopologicalRing A]

omit [IsTopologicalRing A] in
/-- The localization neighborhoods at `s = 1`, `T = {1}` are exactly the images of `I^n`
under `algebraMap ∘ A₀.subtype`. This identifies the localization topology basis with
the original topology basis from `PairOfDefinition.hasBasis_nhds_zero`. -/
theorem locNhd_singleton_one_eq (P : PairOfDefinition A) (n : ℕ) :
    (locNhd P {1} (1 : A) n : Set (Localization.Away (1 : A))) =
      (algebraMap A (Localization.Away (1 : A))) ''
        (Subtype.val '' ((P.I ^ n : Ideal P.A₀) : Set P.A₀)) := by
  ext x; constructor
  · rintro ⟨d, hd, rfl⟩
    rw [locIdeal, ← Ideal.map_pow] at hd
    haveI : RingHomSurjective (algebraMapD P {1} (1 : A)) :=
      ⟨algebraMapD_surjective_one P⟩
    rw [Ideal.map_eq_submodule_map] at hd
    obtain ⟨b, hb, rfl⟩ := Submodule.mem_map.mp hd
    exact ⟨↑b, ⟨b, hb, rfl⟩, rfl⟩
  · rintro ⟨_, ⟨b, hb, rfl⟩, rfl⟩
    exact ⟨algebraMapD P {1} 1 b,
      by rw [locIdeal, ← Ideal.map_pow]; exact Ideal.mem_map_of_mem _ hb, rfl⟩

/-- At `s = 1`, `T = {1}`, the localization topology has the same neighborhood basis
of `0` as the original topology on `A`, mapped through `algebraMap`. Combined with
`PairOfDefinition.hasBasis_nhds_zero`, this shows the localization topology at `s = 1`
corresponds to the original topology under `localizationAwayOneEquiv` (Remark 8.3). -/
theorem locTopology_hasBasis_singleton_one (P : PairOfDefinition A) :
    letI := locTopology P {1} (1 : A) (hopen_away_one P {1})
    (nhds (0 : Localization.Away (1 : A))).HasBasis (fun _ : ℕ => True)
      (fun n => (algebraMap A (Localization.Away (1 : A))) ''
        (Subtype.val '' ((P.I ^ n : Ideal P.A₀) : Set P.A₀))) :=
  (locBasis P {1} 1 (hopen_away_one P {1})).hasBasis_nhds_zero.congr
    (fun _ => Iff.rfl) (fun n _ => locNhd_singleton_one_eq P n)

end Remark83Topology

end Spv
