/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import «Adic spaces».LaurentRefinement
import «Adic spaces».LaurentRefinementTree
import «Adic spaces».EmbeddingTopo
import «Adic spaces».StandardCover
import «Adic spaces».StructureSheaf
import «Adic spaces».RelativeRationalLocData

/-!
# Residual mathematical statements for completing Tate acyclicity

This file collects, **as Lean theorem statements with `sorry` bodies**,
the remaining mathematical results needed to close Wedhorn Theorem
8.28(b) and its `IsSheafy` upgrade unconditionally.

## Critical-path structure

* **Group I** — closes the topological-inducing side of `IsSheafy`
  via the Laurent-refinement-tree route (round-5 reviewer-confirmed).
* **Group II** — closes the algebraic separation + gluing.
* **Group III** — foundational analytic transitivity bridge.
* **Group IV** — Spa-point existence input (adic Nullstellensatz).
* **Group V** — Mathlib gaps (external dependencies).

Each statement is given the natural Lean signature; the body is
`:= by sorry` so the file compiles (with `sorry`-warnings).
-/

namespace ValuationSpectrum

section Residuals

variable {A : Type*} [CommRing A] [TopologicalSpace A] [PlusSubring A]
  [IsTopologicalRing A] [IsHuberRing A] [HasLocLiftPowerBounded A]

/-! ## Group I — Topological-inducing side -/

/-- **(I.1) Wedhorn Lemma 8.34 (constructive tree existence).**
The headliner residual for the `IsSheafy` embedding. Given any
rational covering `C` of a base datum, exhibit a Laurent refinement
tree refining `C` with the inducing and disjointness predicates
that feed `productRestrictionSub_isInducing_via_tree_refinement`.

Per round-5 reviewer guidance, this is built as a **grafted Wedhorn
tree**: an outer balanced Laurent tree from a standard cover
(Cor 7.32 normalisation, theorem I.2 below), each of whose leaves
is refined by a second-stage Laurent ratio cover (theorem I.3
below), assembled via the graft + prune operations (theorem I.4). -/
theorem exists_wedhorn_laurent_refinement_tree
    [IsTateRing A] [IsNoetherianRing A] [IsStronglyNoetherian A] [T2Space A]
    [NonarchimedeanRing A] [IsDomain A]
    (P : PairOfDefinition A) [IsNoetherianRing P.A₀]
    (C : RationalCovering A) :
    ∃ t : LaurentTree A,
      t.Refines C.base C ∧
      t.allSplitsInducing C.base ∧
      t.allNodesDisjoint C.base := by
  sorry

/-- **(I.2) First-stage Laurent cover via Corollary 7.32
normalisation.** Given a standard cover `S` refining a rational
covering `C`, produce a dominating unit `s` and the balanced Laurent
refinement tree on the rescaled list `{s⁻¹ · f : f ∈ S}`, such that
at every leaf `L` of this tree, the restriction of the standard cover
`U` to `L` is generated by a finite family of units in `𝒪_X(L)`. The
unit-generating family is local to each leaf. -/
theorem exists_first_stage_laurent_cover
    [IsTateRing A] [IsNoetherianRing A] [IsStronglyNoetherian A] [T2Space A]
    [NonarchimedeanRing A] [IsDomain A]
    [DecidableEq A]
    (P : PairOfDefinition A) [IsNoetherianRing P.A₀]
    (C : RationalCovering A)
    (S : Finset A)
    (_hS_cover : refines_cover C S)
    (_hS_contain : refines_contain C S)
    (_hS_span : refines_span_top S) :
    ∃ (s : Aˣ) (V_list : List A) (V : LaurentTree A),
      V = LaurentTree.ofBalancedList V_list ∧
      -- The rescaled list is {s⁻¹ · f : f ∈ S} (using s⁻¹ ∈ Aˣ coerced to A).
      V_list = (S.toList).map (fun f => ((s⁻¹ : Aˣ) : A) * f) ∧
      -- At every leaf L, U|L is generated by units in 𝒪_X(L). Precisely:
      -- there is a finite family of units in 𝒪_X(L) whose rational
      -- cover over L coincides with the restriction of the
      -- standard-cover U at S to L.
      ∀ L ∈ V.leaves C.base,
        ∃ units : Finset (presheafValue L),
          (∀ u ∈ units, IsUnit u) ∧
          -- "Generated by units" predicate: the restricted cover U|L
          -- (= the cover of L whose pieces are
          --  R(insert f C.base.T / C.base.s) ∩ rationalOpen L
          --  for f ∈ S) coincides with the rational cover of L
          --  generated by `units`. The precise predicate is the
          --  "cover-by-units" form used in Wedhorn pp. 83-84.
          True := by
  sorry

/-- **(I.3) Second-stage Laurent refinement of a unit-generated
cover.** A rational cover whose pieces are determined by a finite
family of units (each piece being a Laurent-plus condition at one
unit) is refined by the Laurent cover generated by the pairwise
ratios of those units.

The refinement assignment is via valuation ordering: at every `v`,
the unique unit with maximal `v`-value selects a single piece of
the original cover.

Note: the ratios `uᵢ · uⱼ⁻¹` live in the leaf's presheaf value, NOT
in `A` directly. Encoding the resulting split as either a relative
rational locality datum over `presheafValue L` or as an absolute
datum over `A` via denominator clearing requires the transitivity
API (Group III). -/
theorem exists_unit_generated_laurent_refinement
    [IsTateRing A] [IsNoetherianRing A] [IsStronglyNoetherian A] [T2Space A]
    [NonarchimedeanRing A]
    (L : RationalLocData A)
    (units : Finset (presheafValue L))
    (_h_units : ∀ u ∈ units, IsUnit u) :
    -- There exists a Laurent refinement tree (in the generalised
    -- `RatioLaurentTree A` sense, with `nodeRatio` constructors for
    -- the ratio splits) whose leaves refine the rational cover of
    -- `L` generated by `units`.
    ∃ t : RatioLaurentTree A, t.depth = units.card * (units.card - 1) / 2 := by
  sorry

/-- **(I.4) Grafted-tree `allNodesDisjoint` preservation via prune.**
The graft operation expands the per-node sub-coverings beyond the
outer tree's original Finsets; the resulting `allNodesDisjoint`
fails in general. A pruning operation that deduplicates the merged
Finsets at each node restores `allNodesDisjoint` while preserving
the represented cover and `allSplitsInducing`. -/
theorem allNodesDisjoint_graftAt_prune
    [IsTateRing A] [IsNoetherianRing A] [T2Space A] [NonarchimedeanRing A]
    [IsDomain A]
    (t_outer : LaurentTree A) (D₀ : RationalLocData A)
    (h : RationalLocData A → LaurentTree A)
    (_h_outer_disj : t_outer.allNodesDisjoint D₀)
    (_h_inner_disj : ∀ L ∈ t_outer.leaves D₀, (h L).allNodesDisjoint L) :
    -- After pruning, the grafted tree satisfies `allNodesDisjoint`.
    -- The `prune` operation itself is a separate piece to define.
    ∃ t_pruned : LaurentTree A,
      t_pruned.toCovering D₀ = (t_outer.graftAt D₀ h).toCovering D₀ ∧
      t_pruned.allNodesDisjoint D₀ := by
  sorry

/-! ## Group II — Algebraic side -/

/-- **(II.1) Tate acyclicity Part 1 — separation (routing wrapper).**
For a strongly noetherian Tate ring, any rational covering, the
diagonal restriction is injective on global sections. The
mathematical content is already established in `Cor832.lean` as
`productRestriction_injective_tate_of_hSpa_points`; this is the
**downstream wrapper** that invokes it from `tateAcyclicity`'s
location (currently blocked by Lean import cycle).

Status: pure routing, no new mathematics. -/
theorem tateAcyclicity_part1_separation_via_cor832
    [IsTateRing A] [IsNoetherianRing A] [IsStronglyNoetherian A] [T2Space A]
    [NonarchimedeanRing A] [IsDomain A]
    (P : PairOfDefinition A) [IsNoetherianRing P.A₀]
    (C : RationalCovering A) (_hne : C.covers.Nonempty)
    -- Spa-point existence input (= residual IV.1 below).
    (_hSpa : ∀ (p : Ideal A), p.IsPrime → C.base.s ∉ p →
      ∃ v ∈ rationalOpen C.base.T C.base.s, p ≤ v.supp) :
    ∀ x : presheafValue C.base,
      (∀ (D : RationalLocData A) (hD : D ∈ C.covers),
        restrictionMap C.base D (C.hsubset D hD) x = 0) → x = 0 := by
  sorry

/-- **(II.2) Tate acyclicity Part 2 — gluing via faithful-flat
descent (Stacks Tag 023N).** A compatible family of sections in the
product `∏ 𝒪_X(D)` lifts to a global section in `𝒪_X(C.base)`.

Mathematical content: combine faithful flatness of the product
restriction (Corollary 8.32, proved) with the **flat descent
equaliser identification** (Stacks Tag 023N) — for a faithfully flat
ring map `A → B`, the sequence `M → M ⊗ B ⇒ M ⊗ B ⊗ B` is an
equaliser. The compatible-family hypothesis says the image lies in
the equaliser; descent gives the preimage. -/
theorem tateAcyclicity_part2_gluing_via_flat_descent
    [IsTateRing A] [IsNoetherianRing A] [IsStronglyNoetherian A] [T2Space A]
    [NonarchimedeanRing A] [IsDomain A]
    (P : PairOfDefinition A) [IsNoetherianRing P.A₀]
    (C : RationalCovering A) (_hne : C.covers.Nonempty)
    (_hSpa : ∀ (p : Ideal A), p.IsPrime → C.base.s ∉ p →
      ∃ v ∈ rationalOpen C.base.T C.base.s, p ≤ v.supp)
    (f : ∀ D : ↥C.covers, presheafValue D.1)
    (_hcompat : ∀ (D₁ D₂ : ↥C.covers) (D₃ : RationalLocData A)
      (h₃₁ : rationalOpen D₃.T D₃.s ⊆ rationalOpen D₁.1.T D₁.1.s)
      (h₃₂ : rationalOpen D₃.T D₃.s ⊆ rationalOpen D₂.1.T D₂.1.s),
      restrictionMap D₁.1 D₃ h₃₁ (f D₁) = restrictionMap D₂.1 D₃ h₃₂ (f D₂)) :
    ∃ x : presheafValue C.base, ∀ (D : ↥C.covers),
      restrictionMap C.base D.1 (C.hsubset D.1 D.2) x = f D := by
  sorry

/-! ## Group III — Transitivity bridge (foundational) -/

/-- **(III.1) `presheafValue_relative_equiv`: depth-N Wedhorn Lemma
2.13 at the topological level.** For nested rational locality data
`E ⊆ D` (= `rationalOpen D ⊆ rationalOpen E`) with `D` Laurent-
normalised, the relative datum
`relativeRationalLocData_laurentNormalized P E D` (already constructed
in the project) has its presheaf value canonically isomorphic — as a
**topological ring** — to the absolute `presheafValue D`. The
isomorphism intertwines the restriction map with the canonical map
at the `E`-level.

This is the foundational transitivity bridge unblocking Group I.3. -/
noncomputable def presheafValue_relative_equiv
    [IsTateRing A] [IsNoetherianRing A] [T2Space A] [NonarchimedeanRing A]
    (P : PairOfDefinition A) [IsNoetherianRing P.A₀]
    (E : RationalLocData A) [IsNoetherianRing (locSubring E.P E.T E.s)]
    (D : RationalLocData A) [LaurentNormalized D]
    (hsub : rationalOpen D.T D.s ⊆ rationalOpen E.T E.s) :
    presheafValue D ≃+*
      letI : IsTateRing (presheafValue E) := presheafValue_isTateRing P E
      letI : DecidableEq (presheafValue E) := Classical.decEq _
      presheafValue (relativeRationalLocData_laurentNormalized P E D hsub) := by
  sorry

/-- **(III.2) Topological-isomorphism upgrade.** The ring-level
equivalence of III.1 is in fact a **homeomorphism** with respect to
the natural topologies on both sides. -/
theorem presheafValue_relative_equiv_isHomeomorph
    [IsTateRing A] [IsNoetherianRing A] [T2Space A] [NonarchimedeanRing A]
    (P : PairOfDefinition A) [IsNoetherianRing P.A₀]
    (E : RationalLocData A) [IsNoetherianRing (locSubring E.P E.T E.s)]
    (D : RationalLocData A) [LaurentNormalized D]
    (hsub : rationalOpen D.T D.s ⊆ rationalOpen E.T E.s) :
    -- Continuity of both directions of the ring iso.
    True := by
  sorry

/-- **(III.3) Power-bounded generators of relative rational data.**
The replacement target for the obviated `T-LOCLIFT-PRESERVATION`
(the explicit `HasLocLiftPowerBounded` preservation). Under the
transitivity isomorphism III.1, the canonical fraction-generators
of the relative datum (when expressed as iterated fractions over `A`)
are power-bounded in the corresponding `locSubring`/`PlusSubring`. -/
theorem relativeRationalLocData_generators_powerBounded
    [IsTateRing A] [IsNoetherianRing A] [T2Space A] [NonarchimedeanRing A]
    (P : PairOfDefinition A) [IsNoetherianRing P.A₀]
    (E : RationalLocData A) [IsNoetherianRing (locSubring E.P E.T E.s)]
    (D : RationalLocData A) [LaurentNormalized D]
    (_hsub : rationalOpen D.T D.s ⊆ rationalOpen E.T E.s) :
    -- Each generator of the relative datum's locSubring is
    -- power-bounded under the appropriate topology.
    True := by
  sorry

/-! ## Group IV — Spa-point existence (adic Nullstellensatz) -/

/-- **(IV.1) Wedhorn Proposition 7.14 / Hübner adic Nullstellensatz
(unconditional).** For a strongly noetherian Tate ring, any rational
locality datum `D₀`, any prime ideal `p ⊂ A` with `D₀.s ∉ p`, there
exists a continuous valuation `v ∈ rationalOpen D₀.T D₀.s ⊆ Spa(A, A⁺)`
with `p ≤ supp(v)`.

This is the `hSpa` hypothesis currently carried at consumer level
(used in `refines_by_standard_cover` and
`productRestriction_injective_tate_of_hSpa_points`). An unconditional
proof requires the adic Nullstellensatz — a valuation-theoretic
construction. -/
theorem exists_spa_point_dominating_prime
    [IsTateRing A] [IsNoetherianRing A] [IsStronglyNoetherian A] [T2Space A]
    [NonarchimedeanRing A]
    (D₀ : RationalLocData A) (p : Ideal A) (_hp : p.IsPrime)
    (_hs : D₀.s ∉ p) :
    ∃ v ∈ rationalOpen D₀.T D₀.s, p ≤ v.supp := by
  sorry

/-! ## Group V — Mathlib external dependencies -/

/-- **(V.1) Stacks Project Tag 00MA.** The `I`-adic completion of a
noetherian commutative ring is noetherian.

Used in `T-STRONG-NOETH-PRESERVATION-FULL` to propagate strong
noetherianity (= noetherianity of multivariable restricted-power-
series rings) through rational localisations. Currently a Mathlib
gap; affects multivariable-Tate-algebra Noetherianity preservation.

Statement uses `AdicCompletion`. -/
theorem adicCompletion_noetherian
    (R : Type*) [CommRing R] [IsNoetherianRing R]
    (I : Ideal R) :
    IsNoetherianRing (AdicCompletion I R) := by
  sorry

/-- **(V.2) Stacks Project Tag 023N (flat descent equaliser).** For
a faithfully flat ring map `φ : R → S` and an `R`-module `M`, the
sequence
> M → M ⊗_R S ⇒ M ⊗_R S ⊗_R S
is an equaliser of `R`-modules, where the two parallel maps
`M ⊗ S ⇒ M ⊗ S ⊗ S` are induced by `s ↦ s ⊗ 1` (left)
and `s ↦ 1 ⊗ s` (right) on the second factor.

Used in Group II.2 (gluing). Mathlib may have a form; if not, this
is the precise required statement. The Lean formulation needs care
around the exact `TensorProduct` API for the two parallel maps;
stated here at the existence level only. -/
theorem flat_descent_equaliser
    {R : Type*} [CommRing R] {S : Type*} [CommRing S] [Algebra R S]
    [Module.FaithfullyFlat R S]
    (M : Type*) [AddCommGroup M] [Module R M]
    (_x : TensorProduct R M S) :
    -- The full statement: `_x` lies in the equaliser of the two
    -- parallel maps `M ⊗ S ⇒ M ⊗ S ⊗ S` iff `_x` is in the image
    -- of the inclusion `M → M ⊗ S` given by `m ↦ m ⊗ 1`. Stated
    -- abstractly here as a placeholder for the precise Lean form.
    True := by
  sorry

end Residuals

/-! ## Soundness check — combining the residuals proves Tate acyclicity

This section verifies the dependency graph closes: assuming every
residual above is proved sorry-free, the headline theorems
(`tateAcyclicityComplete` and `isSheafyComplete`) follow by pure
composition with existing axiom-clean infrastructure. -/

section Closure

variable {A : Type u_1} [CommRing A] [TopologicalSpace A] [PlusSubring A]
  [IsTopologicalRing A] [IsHuberRing A] [HasLocLiftPowerBounded A]

/-- **Closure (1): Tate acyclicity from Group II + Group IV.**

Discharges both Part 1 (separation) and Part 2 (gluing) by combining:
* `tateAcyclicity_part1_separation_via_cor832` (II.1),
* `tateAcyclicity_part2_gluing_via_flat_descent` (II.2),
* `exists_spa_point_dominating_prime` (IV.1, supplies `hSpa`).

Once II.1, II.2, IV.1 are sorry-free, this theorem proves Tate
acyclicity unconditionally — no further input needed. -/
theorem tateAcyclicityComplete
    [IsTateRing A] [IsNoetherianRing A] [IsStronglyNoetherian A] [T2Space A]
    [NonarchimedeanRing A] [IsDomain A]
    (P : PairOfDefinition A) [IsNoetherianRing P.A₀]
    (C : RationalCovering A) (hne : C.covers.Nonempty) :
    -- Part 1: separation.
    (∀ x : presheafValue C.base,
      (∀ (D : RationalLocData A) (hD : D ∈ C.covers),
        restrictionMap C.base D (C.hsubset D hD) x = 0) → x = 0) ∧
    -- Part 2: gluing.
    (∀ (f : ∀ D : ↥C.covers, presheafValue D.1),
      (∀ (D₁ D₂ : ↥C.covers) (D₃ : RationalLocData A)
        (h₃₁ : rationalOpen D₃.T D₃.s ⊆ rationalOpen D₁.1.T D₁.1.s)
        (h₃₂ : rationalOpen D₃.T D₃.s ⊆ rationalOpen D₂.1.T D₂.1.s),
        restrictionMap D₁.1 D₃ h₃₁ (f D₁) = restrictionMap D₂.1 D₃ h₃₂ (f D₂)) →
      ∃ x : presheafValue C.base, ∀ (D : ↥C.covers),
        restrictionMap C.base D.1 (C.hsubset D.1 D.2) x = f D) := by
  -- The Spa-point existence hypothesis is supplied by IV.1.
  have hSpa : ∀ (p : Ideal A), p.IsPrime → C.base.s ∉ p →
      ∃ v ∈ rationalOpen C.base.T C.base.s, p ≤ v.supp :=
    fun p hp hs => exists_spa_point_dominating_prime C.base p hp hs
  refine ⟨?_, ?_⟩
  · -- Part 1 via II.1.
    exact tateAcyclicity_part1_separation_via_cor832 P C hne hSpa
  · -- Part 2 via II.2.
    intro f hcompat
    exact tateAcyclicity_part2_gluing_via_flat_descent P C hne hSpa f hcompat

/-- **Closure (2): `IsSheafy` from Group I + Group II + Group IV.**

Discharges the full `IsSheafy A` structure by combining:
* `exists_wedhorn_laurent_refinement_tree` (I.1) — the Wedhorn 8.34
  constructive tree, supplied to
  `productRestrictionSub_isInducing_of_wedhorn_tree_existence`
  (existing, axiom-clean) for the topological-inducing side;
* `exists_spa_point_dominating_prime` (IV.1) — supplies `hSpa`;
* The existing `isSheafy_ofStronglyNoetherianTate_flat_of_wedhorn_tree_existence`
  (axiom-clean, in EmbeddingTopo.lean) composes everything.

Once I.1 and IV.1 are sorry-free, this theorem proves `IsSheafy A`
unconditionally — no further input needed. -/
theorem isSheafyComplete
    [IsTateRing A] [IsNoetherianRing A] [IsStronglyNoetherian A] [T2Space A]
    [NonarchimedeanRing A] [IsDomain A]
    (P : PairOfDefinition A) [IsNoetherianRing P.A₀] :
    IsSheafy A := by
  refine isSheafy_ofStronglyNoetherianTate_flat_of_wedhorn_tree_existence
    P ?_ ?_
  · -- Spa-point existence via IV.1.
    intro C p hp hs
    exact exists_spa_point_dominating_prime C.base p hp hs
  · -- Wedhorn 8.34 tree existence via I.1.
    intro C
    exact exists_wedhorn_laurent_refinement_tree P C

/-! ### Dependency-graph summary

```
                                    ┌─────────────────────────────┐
                                    │  Group V (Mathlib)          │
                                    │  V.1 Stacks 00MA            │
                                    │  V.2 Stacks 023N            │
                                    └──────────────┬──────────────┘
                                                   │
                ┌──────────────────────────────────┴──────────┐
                │                                              │
                ▼                                              ▼
┌─────────────────────────────┐                ┌─────────────────────────────┐
│  Group III (transitivity)   │                │  Group II (algebraic)        │
│  III.1 presheafValue_rel    │                │  II.2 uses V.2               │
│  III.2 isHomeo              │                └──────────────┬──────────────┘
│  III.3 powerBounded         │                               │
└──────────────┬──────────────┘                               │
               │                                              │
               ▼                                              ▼
┌─────────────────────────────┐    ┌──────────────────────────────────────┐
│  Group I (top-inducing)     │    │  Group IV (Spa-points)               │
│  I.2 first stage            │    │  IV.1 Wedhorn 7.14 / Nullstellensatz │
│  I.3 second stage (uses III)│    └──────────────────────┬───────────────┘
│  I.4 prune                  │                           │
│  I.1 assembled tree         │                           │
└──────────────┬──────────────┘                           │
               │                                          │
               ▼                                          │
    ┌──────────────────────────────┐                      │
    │  isSheafyComplete            │                      │
    │  (consumes I.1 + IV.1)       │◄─────────────────────┘
    └──────────────────────────────┘
                                                          │
    ┌──────────────────────────────┐                      │
    │  tateAcyclicityComplete      │                      │
    │  (consumes II.1+II.2+IV.1)   │◄─────────────────────┘
    └──────────────────────────────┘
```

**Conclusion**: every leaf of the residual DAG either is (a) one of
the 12 stated theorems above, (b) an already-proved-axiom-clean
piece of the project (`Cor832.lean`,
`productRestrictionSub_isInducing_of_wedhorn_tree_existence`,
`isSheafy_..._of_wedhorn_tree_existence`, etc.), or (c) a Mathlib
external (V.1, V.2). The closure proofs `tateAcyclicityComplete` and
`isSheafyComplete` show pure composition closes the goal. -/

end Closure

end ValuationSpectrum
