/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import «Adic spaces».ValuationSpectrum
import Mathlib.Topology.Compactness.Compact
import Mathlib.Topology.Constructions

/-!
# Compactness of the Valuation Spectrum (scaffolding)

This file begins the port of Huber's proof that `Spv A = ValuationSpectrum A` is a
**quasi-compact** topological space (Wedhorn, Theorem 4.9; Huber, *Continuous valuations*,
1993, Lemma 2.1 / Theorem 3.1).

## High-level strategy

The argument embeds `Spv A` into the function space `(A × A) → Prop`, equipped with the
product topology (each factor carrying the Sierpinski topology on `Prop`, under which
`{True}` is the only non-trivial open). Tychonoff gives `CompactSpace (A × A → Prop)`
(the Sierpinski space is compact, and an arbitrary product of compact spaces is compact).
To deduce compactness of `Spv A` one shows:

* `ιSpv` is a topological embedding (`ιSpv_isEmbedding`);
* the image of `ιSpv` inside `(A × A → Prop)` is a **closed subset** (Phase 2).

A closed subspace of a compact space is compact, giving `CompactSpace (Spv A)`.

## Choice of embedding: basic-open characteristic functions

The most natural-looking embedding would be `v ↦ (f, s) ↦ v.vle f s` (a direct
characteristic function of the valuative preorder). **However, that embedding does not
induce the right topology on `Spv A`.** The Sierpinski topology has only `{True}` open,
so the sub-basic pullback `{v | v.vle f s}` would be forced to be open in `Spv A` — but
this set is *not* open in `Spv A` in general (it fails to be closed under specialisations
that move `s` into the support). The topology on `Spv A` is generated by the strictly
stronger conditions `basicOpen f s = {v | v.vle f s ∧ ¬ v.vle s 0}`.

The fix is to take the coordinate to be the conjunction directly:

  `ιSpv v (f, s) := v.vle f s ∧ ¬ v.vle s 0`,  i.e. `v ∈ basicOpen f s`.

With this choice, the Sierpinski sub-basic pullback at coordinate `(f, s)` is exactly
`basicOpen f s`, which is open in `Spv A` by definition of the topology; conversely every
generator of the topology on `Spv A` arises as such a pullback. Hence the product topology
restricts to the given topology on `Spv A` and `ιSpv` is a topological embedding.

Injectivity still holds: the support information carried by the coordinate `(s, s)`
(specifically, `v ∈ basicOpen s s ↔ ¬ v.vle s 0`) combined with the coordinates `(f, f)`
(telling us when `f ∈ supp v`, via `v ∈ basicOpen f f ↔ ¬ v.vle f 0`) is enough to recover
the raw valuative preorder `v.vle f s`.

## Contents of this file (Phase 1 — embedding only)

* `ValuationSpectrum.ιSpv` — the Huber embedding (basic-open characteristic form).
* `ValuationSpectrum.ιSpv_apply` — definitional unfolding.
* `ValuationSpectrum.vle_iff_of_ιSpv` — recovers `v.vle f s` from `ιSpv` values.
* `ValuationSpectrum.ιSpv_injective` — injectivity.
* `ValuationSpectrum.ιSpv_isInducing` — topology agreement.
* `ValuationSpectrum.ιSpv_isEmbedding` — the main embedding theorem.

## Future work (Phase 2 — not in this file yet)

* Prove the image of `ιSpv` is a closed subset of `(A × A → Prop)`. Concretely, express
  the fact that `r` arises from a valuation in terms of closed conditions in the product
  (each a finite boolean combination of coordinate sub-basics).
* Conclude `CompactSpace (Spv A)` from Tychonoff + closed-subspace compactness + the
  embedding proved here.

## References

* T. Wedhorn, *Adic Spaces*, Theorem 4.9.
* R. Huber, *Continuous valuations*, Math. Z. 212 (1993), 455–477.
-/

namespace ValuationSpectrum

variable {A : Type*} [CommRing A]

/-! ### The Huber embedding `ιSpv : Spv A → (A × A → Prop)` -/

/-- **Huber embedding.** Send a point `v ∈ Spv A` to the characteristic function of its
basic opens: `(f, s) ↦ v ∈ basicOpen f s`, unfolded as `v.vle f s ∧ ¬ v.vle s 0`.

With `Prop` carrying the Sierpinski topology and `A × A → Prop` the product topology, the
sub-basic open set `{r | r (f, s)}` pulls back to `basicOpen f s`, which is precisely one
of the generating opens of the topology on `Spv A`. Hence the induced topology agrees with
the given topology on `Spv A` (see `ιSpv_isInducing`). -/
def ιSpv (v : Spv A) : A × A → Prop := fun p => v.vle p.1 p.2 ∧ ¬ v.vle p.2 0

@[simp]
lemma ιSpv_apply (v : Spv A) (f s : A) :
    ιSpv v (f, s) = (v.vle f s ∧ ¬ v.vle s 0) := rfl

/-- The coordinate `(f, s)` of `ιSpv v` exactly tests membership in `basicOpen f s`. -/
lemma ιSpv_iff_mem_basicOpen (v : Spv A) (f s : A) :
    ιSpv v (f, s) ↔ v ∈ basicOpen f s := Iff.rfl

/-- The coordinate `(s, s)` of `ιSpv v` tests whether `s` lies outside the support. -/
lemma ιSpv_diag (v : Spv A) (s : A) : ιSpv v (s, s) ↔ ¬ v.vle s 0 := by
  simp [ιSpv]

/-- The raw valuative preorder `v.vle f s` can be recovered from the `ιSpv` data.

If `¬ v.vle s 0` (i.e. `s ∉ supp v`) then `v.vle f s` is simply the `(f, s)` coordinate.
If `v.vle s 0` (i.e. `s ∈ supp v`) then `v.vle f s ↔ v.vle f 0`, which can be recovered
from the negations of the `(s, s)` and `(f, f)` coordinates (via `ιSpv_diag`). -/
lemma vle_iff_ιSpv (v : Spv A) (f s : A) :
    v.vle f s ↔ (ιSpv v (f, s) ∨ (¬ ιSpv v (s, s) ∧ ¬ ιSpv v (f, f))) := by
  rw [ιSpv_diag, ιSpv_diag]
  simp only [not_not, ιSpv_apply]
  constructor
  · intro h
    by_cases hs : v.vle s 0
    · exact Or.inr ⟨hs, v.vle_trans h hs⟩
    · exact Or.inl ⟨h, hs⟩
  · rintro (⟨h, _⟩ | ⟨_, hf⟩)
    · exact h
    · exact v.vle_trans hf (v.zero_vle s)

/-- The Huber embedding is injective: two points of `Spv A` with equal basic-open
characteristic functions are equal. -/
lemma ιSpv_injective : Function.Injective (ιSpv : Spv A → _) := by
  intro v₁ v₂ h
  apply ValuationSpectrum.ext
  funext f s
  have key : ∀ f s : A, ιSpv v₁ (f, s) ↔ ιSpv v₂ (f, s) := by
    intro f s; exact (congrArg (fun r => r (f, s)) h).to_iff
  exact propext <| by
    rw [vle_iff_ιSpv, vle_iff_ιSpv]
    simp only [key]

/-! ### `ιSpv` is a topological embedding -/

/-- The topology on `Spv A` coincides with the topology induced from the product topology
on `(A × A → Prop)` (product of Sierpinski). -/
lemma ιSpv_isInducing : Topology.IsInducing (ιSpv : Spv A → (A × A → Prop)) := by
  refine ⟨?_⟩
  -- Unfold Pi topology to an iInf of single-coordinate induced topologies.
  rw [show (Pi.topologicalSpace :
      TopologicalSpace (A × A → Prop)) = ⨅ p, TopologicalSpace.induced
        (fun r : A × A → Prop => r p) sierpinskiSpace from rfl]
  rw [induced_iInf]
  -- Each coordinate's pullback of the Sierpinski generator is a basic open.
  have hcoord : ∀ p : A × A,
      TopologicalSpace.induced ((fun r : A × A → Prop => r p) ∘ ιSpv) sierpinskiSpace =
        TopologicalSpace.generateFrom {basicOpen p.1 p.2} := by
    intro p
    rw [show sierpinskiSpace = TopologicalSpace.generateFrom {{True}} from rfl,
        induced_generateFrom_eq]
    congr 1
    ext s
    refine ⟨?_, ?_⟩
    · rintro ⟨t, ht, rfl⟩
      rw [Set.mem_singleton_iff] at ht
      subst ht
      refine Set.mem_singleton_iff.mpr ?_
      ext v
      simp [Function.comp, ιSpv, basicOpen]
    · rintro hs
      rw [Set.mem_singleton_iff] at hs
      refine ⟨{True}, Set.mem_singleton _, ?_⟩
      subst hs
      ext v
      simp [Function.comp, ιSpv, basicOpen]
  simp_rw [induced_compose, hcoord]
  -- Match the iInf of single-generator topologies to the Spv topology.
  rw [show (⨅ p : A × A, TopologicalSpace.generateFrom {basicOpen p.1 p.2}) =
      TopologicalSpace.generateFrom (⋃ p : A × A, {basicOpen p.1 p.2}) from
      generateFrom_iUnion.symm]
  unfold ValuationSpectrum.instTopologicalSpace
  congr 1
  ext U
  simp only [Set.mem_iUnion, Set.mem_singleton_iff, Set.mem_setOf_eq, Prod.exists]

/-- **Huber embedding — Phase 1 main result.** The map `ιSpv : Spv A → (A × A → Prop)`
is a topological embedding (injective + induced topology agrees).

This is the content of the topological half of Wedhorn's Theorem 4.9 / Huber 1993, Lemma
2.1. The compactness conclusion additionally requires closedness of the image, which is
deferred to Phase 2. -/
theorem ιSpv_isEmbedding : Topology.IsEmbedding (ιSpv : Spv A → (A × A → Prop)) where
  eq_induced := ιSpv_isInducing.eq_induced
  injective := ιSpv_injective

/-! ### Phase 2 TODO (not proven here)

The remaining step towards `CompactSpace (Spv A)` is to show the image of `ιSpv` is a
closed subset of `(A × A → Prop)`. This image is cut out by the axioms of a valuation in
the basic-open form:

```
/-- The image of the Huber embedding is closed in the product topology. -/
lemma isClosed_range_ιSpv : IsClosed (Set.range (ιSpv : Spv A → (A × A → Prop))) := ...

/-- **Huber — Wedhorn Theorem 4.9.** The valuation spectrum is quasi-compact. -/
instance : CompactSpace (Spv A) := ...
```

The strategy is: Tychonoff gives `CompactSpace ((A × A) → Prop)`; the image of `ιSpv` is
cut out by closed conditions (each of the six `ValuativeRel` axioms can be re-expressed
in terms of the basic-open characteristic values, and each expression is a finite boolean
combination of coordinate sub-basics — hence closed in the Sierpinski product). A closed
subspace of a compact space is compact, and embeddings transport compactness.
-/

end ValuationSpectrum
