/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import «Adic spaces».ValuationSpectrum
import Mathlib.Topology.Compactness.Compact
import Mathlib.Topology.Constructions

/-!
# Compactness of the Valuation Spectrum (scaffolding)

This file begins the port of Huber's proof that `Spv A = ValuationSpectrum A` is a
**quasi-compact** topological space (Wedhorn, Theorem 4.9; Huber, *Continuous valuations*,
1993, Lemma 2.1 / Theorem 3.1).

## High-level strategy

The argument embeds `Spv A` into the function space `(A × A) → Prop`, equipped with the
product topology (each factor carrying the Sierpinski topology). Explicitly, one sets

  `ιSpv : Spv A → (A × A → Prop)`,  `ιSpv v (f, s) = v.vle f s`.

Tychonoff gives `CompactSpace (A × A → Prop)` (the Sierpinski space on `Prop` is compact,
and an arbitrary product of compact spaces is compact). To deduce compactness of `Spv A`
one shows:

* `ιSpv` is a topological embedding: the topology on `Spv A` generated by the basic opens
  `basicOpen f s = {v | v.vle f s ∧ ¬ v.vle s 0}` coincides with the subspace topology
  induced by `ιSpv` (after passing to a sub-basis generated by characteristic maps of
  pairs `(f, s)` and `(s, 0)`).
* The image of `ιSpv` inside `(A × A → Prop)` is a **closed subset**, since it is cut out
  by the `ValuativeRel` axioms, each of which is expressible as an intersection of closed
  conditions in the product.

A closed subspace of a compact space is compact, giving `CompactSpace (Spv A)`.

## Contents of this file (Phase 1 — scaffolding only)

* `ValuationSpectrum.ιSpv` — the Huber embedding.
* `ValuationSpectrum.ιSpv_injective` — injectivity (consequence of `ValuationSpectrum.ext`).
* `ValuationSpectrum.IsValuation` — predicate on `(A × A → Prop)` expressing the six
  `ValuativeRel` axioms in "raw" form. The closed-subset argument in Phase 2 will show that
  each conjunct is a closed condition.
* `ValuationSpectrum.ιSpv_isValuation` — the image of `ιSpv` lies in `{r | IsValuation r}`.

## Future work (Phase 2 — not in this file yet)

* Promote `IsValuation` to a closed subset of the product, axiom by axiom.
* Prove that `ιSpv` is a topological embedding.
* Conclude `CompactSpace (Spv A)` from Tychonoff + closed-subspace compactness.

## Design notes

**Why `Prop` (Sierpinski) and not `Bool` (discrete)?**  `ValuativeRel.vle` is `Prop`-valued,
so `ιSpv` is defined without any decidability hypothesis. The Sierpinski topology on `Prop`
is exactly what is needed: the sub-basic open set `{P : Prop | P}` pulls back along
`fun r => r (f, s)` to `{r | r (f, s)}`, which matches the first half of `basicOpen f s`.
Discrete `Bool` would force a `Decidable` assumption on `vle`, polluting the statement of
the embedding and forcing noncomputable detours.

**Product structure.** We use `(A × A) → Prop` rather than `A → A → Prop` so that the index
type is a single `Type*`, matching the shape of `Pi.topologicalSpace` and `Pi.compactSpace`
cleanly.

## References

* T. Wedhorn, *Adic Spaces*, Theorem 4.9.
* R. Huber, *Continuous valuations*, Math. Z. 212 (1993), 455–477.
-/

namespace ValuationSpectrum

variable {A : Type*} [CommRing A]

/-! ### The Huber embedding `ιSpv : Spv A → (A × A → Prop)` -/

/-- **Huber embedding.** Send a point `v ∈ Spv A` to the characteristic function
`(f, s) ↦ v.vle f s` of its valuative preorder.

This is the starting point of Huber's proof of quasi-compactness of `Spv A`: the image lies
in the closed subset of `(A × A → Prop)` cut out by the `ValuativeRel` axioms, and the
subspace topology agrees with the generator topology on `Spv A`. -/
def ιSpv (v : Spv A) : A × A → Prop := fun p => v.vle p.1 p.2

@[simp]
lemma ιSpv_apply (v : Spv A) (f s : A) : ιSpv v (f, s) = v.vle f s := rfl

/-- The Huber embedding is injective: two points of `Spv A` with the same valuative
preorder are equal (this is precisely `ValuationSpectrum.ext`). -/
lemma ιSpv_injective : Function.Injective (ιSpv : Spv A → _) := by
  intro v₁ v₂ h
  apply ValuationSpectrum.ext
  funext f s
  exact congrArg (fun r => r (f, s)) h

/-! ### The "is a valuation" closed predicate on `(A × A → Prop)` -/

/-- Predicate on `r : A × A → Prop` expressing the six axioms of `ValuativeRel` when
`r (f, s)` is read as `f ≤ᵥ s`.

Each conjunct is a closed condition in the product topology on `(A × A → Prop)` (to be
established in Phase 2), so `{r | IsValuation r}` is a closed subset. The image of `ιSpv`
is exactly this subset (this direction: `ιSpv_isValuation` below; the reverse direction
will be established in Phase 2 by constructing a `ValuativeRel` from any `r` with
`IsValuation r`). -/
structure IsValuation (r : A × A → Prop) : Prop where
  /-- Totality: every pair is comparable. -/
  vle_total : ∀ x y : A, r (x, y) ∨ r (y, x)
  /-- Transitivity. -/
  vle_trans : ∀ {x y z : A}, r (x, y) → r (y, z) → r (x, z)
  /-- Compatibility with addition: if `x, y ≤ᵥ z` then `x + y ≤ᵥ z`. -/
  vle_add : ∀ {x y z : A}, r (x, z) → r (y, z) → r (x + y, z)
  /-- Left multiplication respects the order. -/
  mul_vle_mul_left : ∀ {x y : A} (_ : r (x, y)) (z : A), r (x * z, y * z)
  /-- Multiplicative cancellation: if `z ≠ᵥ 0` and `x * z ≤ᵥ y * z` then `x ≤ᵥ y`. -/
  vle_mul_cancel : ∀ {x y z : A}, ¬ r (z, 0) → r (x * z, y * z) → r (x, y)
  /-- Non-triviality: `1` is never `≤ᵥ 0`. -/
  not_vle_one_zero : ¬ r (1, 0)

/-- The image of the Huber embedding satisfies `IsValuation`: every point of `Spv A` gives
rise to a genuine valuative relation on `A`. -/
lemma ιSpv_isValuation (v : Spv A) : IsValuation (ιSpv v) where
  vle_total x y := v.vle_total x y
  vle_trans h₁ h₂ := v.vle_trans h₁ h₂
  vle_add h₁ h₂ := v.vle_add h₁ h₂
  mul_vle_mul_left h z := v.mul_vle_mul_left h z
  vle_mul_cancel h₀ h := v.vle_mul_cancel h₀ h
  not_vle_one_zero := v.not_vle_one_zero

/-- The range of the Huber embedding is contained in the closed set
`{r | IsValuation r}`. The reverse inclusion (surjectivity onto this set) will be
established in Phase 2 by inverting the embedding. -/
lemma range_ιSpv_subset_isValuation :
    Set.range (ιSpv : Spv A → _) ⊆ { r : A × A → Prop | IsValuation r } := by
  rintro r ⟨v, rfl⟩
  exact ιSpv_isValuation v

/-! ### Phase 2 TODO (not proven here)

The following statements are the planned next steps. We record them only as Lean comments,
not as `sorry`-backed stubs, to keep this file axiom-clean.

```
/-- The Huber embedding is a topological embedding (subspace topology agrees). -/
lemma ιSpv_isEmbedding : Topology.IsEmbedding (ιSpv : Spv A → (A × A → Prop)) := ...

/-- The image of the Huber embedding is closed in the product topology. -/
lemma isClosed_range_ιSpv : IsClosed (Set.range (ιSpv : Spv A → (A × A → Prop))) := ...

/-- Every `r : A × A → Prop` satisfying `IsValuation r` arises from a point of `Spv A`. -/
lemma exists_ιSpv_eq_of_isValuation {r : A × A → Prop} (h : IsValuation r) :
    ∃ v : Spv A, ιSpv v = r := ...

/-- **Huber — Wedhorn Theorem 4.9.** The valuation spectrum is quasi-compact. -/
instance : CompactSpace (Spv A) := ...
```

The strategy is: Tychonoff gives `CompactSpace ((A × A) → Prop)`, and the image of `ιSpv`
is closed (cut out by the six `IsValuation` clauses, each a closed condition). A closed
subspace of a compact space is compact; embeddings transport compactness.
-/

end ValuationSpectrum
