/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.RingTheory.Valuation.ValuativeRel.Basic
import Mathlib.RingTheory.Valuation.Quotient
import Mathlib.RingTheory.Valuation.ExtendToLocalization
import Mathlib.Topology.Order

/-!
# The Valuation Spectrum of a Ring

We define the valuation spectrum `Spv A` of a commutative ring `A`, following
Definition 4.1 of [Wedhorn, *Adic Spaces*].

## Main definitions

* `Spv A` : The valuation spectrum of `A`, the type of `ValuativeRel` instances on `A`.
* `Spv.basicOpen f s` : The basic open set `{ v ∈ Spv A | v(f) ≤ v(s) ≠ 0 }`.
* `Spv.ofValuation v` : Construct a point of `Spv A` from a valuation `v`.
* `Spv.comap φ` : The continuous map `Spv B → Spv A` induced by a ring homomorphism `φ : A →+* B`
  (Remark 4.3 / Proposition 4.7(2) of Wedhorn).
* `Spv.supp v` : The support of `v`, the prime ideal `{ a ∈ A | v(a) = 0 }`.
* `Spv.quotientLift 𝔞 v h` : Lift `v ∈ Spv A` with `𝔞 ≤ supp v` to `Spv (A ⧸ 𝔞)`
  (Remark 4.4(2)).
* `Spv.localizationLift S B v hS` : Lift `v ∈ Spv A` to `Spv B` for a localization `B`
  (Remark 4.4(1)).

## Implementation notes

A point of `Spv A` is an equivalence class of valuations on `A`. Mathlib's `ValuativeRel`
bundles exactly this data: a binary relation `≤ᵥ` on `A` satisfying the axioms of a
valuation-induced preorder. Two valuations are equivalent iff they induce the same
`ValuativeRel` (Proposition 1.27 of Wedhorn), so `Spv A` is defined as a one-field
structure extending `ValuativeRel A`.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn2019adic], Definition 4.1, Remark 4.3, Remark 4.4,
  Proposition 4.7(2)
-/

/-- The *valuation spectrum* `Spv A` of a commutative ring `A` (Definition 4.1 of Wedhorn).
As a set, it consists of equivalence classes of valuations on `A`. We define it as a
one-field structure extending `ValuativeRel A`, each of which encodes a binary relation
arising from a valuation. The topology is generated by the basic open sets
`Spv.basicOpen f s`. -/
@[ext]
structure Spv (A : Type*) [CommRing A] extends ValuativeRel A

namespace Spv

variable {A : Type*} [CommRing A]

/-- Construct a point of `Spv A` from a valuation `v : Valuation A Γ₀`. -/
def ofValuation {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]
    (v : Valuation A Γ₀) : Spv A :=
  ⟨ValuativeRel.ofValuation v⟩

/-- Two equivalent valuations define the same point of `Spv A`. -/
lemma ofValuation_eq_of_isEquiv {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]
    {Γ'₀ : Type*} [LinearOrderedCommGroupWithZero Γ'₀]
    {v₁ : Valuation A Γ₀} {v₂ : Valuation A Γ'₀} (h : v₁.IsEquiv v₂) :
    ofValuation v₁ = ofValuation v₂ :=
  Spv.ext (funext₂ fun x y => propext (h x y))

/-- The basic open subset `Spv(A)(f/s) = { v ∈ Spv A | v(f) ≤ v(s) ∧ v(s) ≠ 0 }`,
where `f, s : A`. These sets generate the topology on `Spv A`. -/
def basicOpen (f s : A) : Set (Spv A) :=
  { v | v.vle f s ∧ ¬ v.vle s 0 }

/-- For `t, f, s : A`, we have `Spv(A)(tf/ts) ⊆ Spv(A)(f/s)`.
Note after Definition 4.1 in Wedhorn. -/
lemma basicOpen_mul_subset (t f s : A) :
    basicOpen (t * f) (t * s) ⊆ basicOpen f s := by
  intro v ⟨h1, h2⟩
  have ht : ¬ v.vle t 0 := by
    intro ht
    exact h2 (by have := v.mul_vle_mul_left ht s; rwa [zero_mul] at this)
  exact ⟨v.vle_mul_cancel ht (by rwa [mul_comm t f, mul_comm t s] at h1),
    fun hs ↦ h2 (by have := v.mul_vle_mul_left hs t; rwa [zero_mul, mul_comm s t] at this)⟩

/-- `Spv(A)(1/1) = Spv A`. Note after Definition 4.1 in Wedhorn. -/
lemma basicOpen_one : basicOpen (1 : A) 1 = Set.univ := by
  ext v
  simp only [basicOpen, Set.mem_setOf_eq, Set.mem_univ, iff_true]
  exact ⟨(v.vle_total 1 1).elim id id, v.not_vle_one_zero⟩

/-- `Spv(A)(s/s) = { v ∈ Spv A | v(s) ≠ 0 }`. Note after Definition 4.1 in Wedhorn. -/
lemma basicOpen_self (s : A) :
    basicOpen s s = { v : Spv A | ¬ v.vle s 0 } := by
  ext v
  simp only [basicOpen, Set.mem_setOf_eq]
  exact ⟨fun ⟨_, h⟩ ↦ h, fun h ↦ ⟨(v.vle_total s s).elim id id, h⟩⟩

/-- The topology on `Spv A` generated by the basic open sets `basicOpen f s`
for `f, s : A`. -/
instance instTopologicalSpace : TopologicalSpace (Spv A) :=
  TopologicalSpace.generateFrom { U | ∃ f s : A, U = basicOpen f s }

/-! ### Functoriality of Spv

A ring homomorphism `φ : A →+* B` induces a continuous map `Spv(φ) : Spv B → Spv A` by
composing valuations with `φ` (Remark 4.3 of Wedhorn). This makes `Spv` a contravariant
functor from commutative rings to topological spaces.
-/

section Functoriality

variable {A B C : Type*} [CommRing A] [CommRing B] [CommRing C]

/-- The pullback of a `ValuativeRel` along a ring homomorphism. Given `φ : A →+* B` and
a valuative relation on `B`, we define a valuative relation on `A` by `a₁ ≤ᵥ a₂ ↔ φ(a₁) ≤ᵥ φ(a₂)`.
This corresponds to composing a valuation on `B` with `φ`. -/
def comapValuativeRel (φ : A →+* B) (v : ValuativeRel B) : ValuativeRel A where
  vle a₁ a₂ := v.vle (φ a₁) (φ a₂)
  vle_total a₁ a₂ := v.vle_total (φ a₁) (φ a₂)
  vle_trans h₁ h₂ := v.vle_trans h₁ h₂
  vle_add h₁ h₂ := by simpa [map_add] using v.vle_add h₁ h₂
  mul_vle_mul_left h z := by simpa [map_mul] using v.mul_vle_mul_left h (φ z)
  vle_mul_cancel h₀ h := by
    rw [show φ 0 = 0 from map_zero φ] at h₀
    simpa [map_mul] using v.vle_mul_cancel h₀ (by simpa [map_mul] using h)
  not_vle_one_zero := by simp [map_one, map_zero, v.not_vle_one_zero]

/-- The contravariant map `Spv B → Spv A` induced by a ring homomorphism `φ : A →+* B`.
This sends a valuation (equivalence class) `v` on `B` to the composition `v ∘ φ` on `A`.
Remark 4.3 / Proposition 4.7(2) of Wedhorn. -/
def comap (φ : A →+* B) (v : Spv B) : Spv A :=
  ⟨comapValuativeRel φ v.toValuativeRel⟩

@[simp]
lemma comap_vle (φ : A →+* B) (v : Spv B) (a₁ a₂ : A) :
    (comap φ v).vle a₁ a₂ = v.vle (φ a₁) (φ a₂) := rfl

/-- `Spv.comap` is compatible with `Spv.ofValuation`: composing a valuation with a ring
homomorphism commutes with the construction of points of `Spv`. -/
lemma comap_ofValuation {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]
    (φ : A →+* B) (v : Valuation B Γ₀) :
    comap φ (ofValuation v) = ofValuation (v.comap φ) := by ext; rfl

/-- Preimage formula for basic open sets under `Spv(φ)`:
`Spv(φ)⁻¹(Spv(A)(f/s)) = Spv(B)(φ(f)/φ(s))`. Equation (4.1.1) of Wedhorn. -/
lemma comap_preimage_basicOpen (φ : A →+* B) (f s : A) :
    comap φ ⁻¹' basicOpen f s = basicOpen (φ f) (φ s) := by
  ext v
  simp only [Set.mem_preimage, basicOpen, Set.mem_setOf_eq, comap_vle, map_zero]

/-- `Spv(φ)` is continuous (Remark 4.3 of Wedhorn). -/
lemma comap_continuous (φ : A →+* B) : Continuous (comap φ) := by
  rw [continuous_generateFrom_iff]
  rintro U ⟨f, s, rfl⟩
  rw [comap_preimage_basicOpen]
  exact TopologicalSpace.isOpen_generateFrom_of_mem ⟨φ f, φ s, rfl⟩

/-- `Spv(id) = id`. -/
@[simp]
lemma comap_id : comap (RingHom.id A) = id := by ext v : 1; ext; rfl

/-- `Spv(ψ ∘ φ) = Spv(φ) ∘ Spv(ψ)` (contravariant functoriality). -/
lemma comap_comp (φ : A →+* B) (ψ : B →+* C) :
    comap (ψ.comp φ) = comap φ ∘ comap ψ := by ext v : 1; ext; rfl

/-- `Spv.comap φ` is injective when `φ` is surjective. -/
lemma comap_injective {φ : A →+* B} (hφ : Function.Surjective φ) :
    Function.Injective (comap φ) := by
  intro v₁ v₂ h
  apply Spv.ext; funext b₁ b₂
  obtain ⟨a₁, rfl⟩ := hφ b₁
  obtain ⟨a₂, rfl⟩ := hφ b₂
  have h₁ := congr_arg (fun v => v.vle a₁ a₂) h
  simpa only [comap_vle] using h₁

end Functoriality

/-! ### Support of a point of `Spv A`

The *support* of a point `v ∈ Spv A` is the prime ideal
`supp(v) = { a ∈ A | v(a) = 0 }`.
-/

/-- The support of a point `v ∈ Spv A`, the prime ideal `{ a ∈ A | v(a) = 0 }`. -/
def supp (v : Spv A) : Ideal A :=
  @ValuativeRel.supp A _ v.toValuativeRel

@[simp]
lemma mem_supp_iff (v : Spv A) (x : A) : x ∈ v.supp ↔ v.vle x 0 :=
  @ValuativeRel.supp_def A _ v.toValuativeRel x

instance instIsPrimeSupp (v : Spv A) : v.supp.IsPrime := by
  rw [show v.supp = @ValuativeRel.supp A _ v.toValuativeRel from rfl,
    @ValuativeRel.supp_eq_valuation_supp A _ v.toValuativeRel]
  infer_instance

lemma supp_ofValuation {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]
    (v : Valuation A Γ₀) : (ofValuation v).supp = v.supp := by
  ext x
  simp only [mem_supp_iff, Valuation.mem_supp_iff]
  change v x ≤ v 0 ↔ v x = 0
  rw [map_zero]
  exact le_zero_iff

/-- The canonical valuation of a `ValuativeRel` gives back the same point of `Spv`. -/
lemma ofValuation_valuation (v : Spv A) :
    ofValuation (@ValuativeRel.valuation A _ v.toValuativeRel) = v := by
  apply Spv.ext; funext x y
  letI : ValuativeRel A := v.toValuativeRel
  exact propext (ValuativeRel.valuation A).vle_iff_le.symm

/-! ### Quotient — Remark 4.4(2) of Wedhorn

For an ideal `𝔞` of `A`, the map `Spv(A ⧸ 𝔞) → Spv A` induced by the quotient
morphism is a topological embedding with range `{ v ∈ Spv A | 𝔞 ≤ supp v }`.
-/

section Quotient

variable (𝔞 : Ideal A)

/-- `𝔞 ≤ supp(comap(mk 𝔞, w))` for all `w : Spv (A ⧸ 𝔞)`. -/
lemma ideal_le_supp_comap_mk (w : Spv (A ⧸ 𝔞)) :
    𝔞 ≤ (comap (Ideal.Quotient.mk 𝔞) w).supp := by
  intro a ha
  simp only [mem_supp_iff, comap_vle, map_zero]
  rw [Ideal.Quotient.eq_zero_iff_mem.mpr ha]
  exact (w.vle_total 0 0).elim id id

/-- Lift a point `v ∈ Spv A` with `𝔞 ≤ supp v` to `Spv (A ⧸ 𝔞)`. -/
noncomputable def quotientLift (v : Spv A) (h : 𝔞 ≤ v.supp) : Spv (A ⧸ 𝔞) :=
  have hJ : 𝔞 ≤ (@ValuativeRel.valuation A _ v.toValuativeRel).supp := by
    rwa [← @ValuativeRel.supp_eq_valuation_supp A _ v.toValuativeRel]
  ofValuation ((@ValuativeRel.valuation A _ v.toValuativeRel).onQuot hJ)

/-- `comap (mk 𝔞) (quotientLift 𝔞 v h) = v`. -/
lemma comap_quotientLift (v : Spv A) (h : 𝔞 ≤ v.supp) :
    comap (Ideal.Quotient.mk 𝔞) (quotientLift 𝔞 v h) = v := by
  simp only [quotientLift, comap_ofValuation, Valuation.onQuot_comap_eq]
  exact ofValuation_valuation v

/-- `quotientLift 𝔞 (comap (mk 𝔞) w) _ = w`. -/
lemma quotientLift_comap (w : Spv (A ⧸ 𝔞)) :
    quotientLift 𝔞 (comap (Ideal.Quotient.mk 𝔞) w) (ideal_le_supp_comap_mk 𝔞 w) = w := by
  apply Spv.ext; funext x y
  obtain ⟨a₁, rfl⟩ := Ideal.Quotient.mk_surjective x
  obtain ⟨a₂, rfl⟩ := Ideal.Quotient.mk_surjective y
  letI : ValuativeRel A := comapValuativeRel (Ideal.Quotient.mk 𝔞) w.toValuativeRel
  exact propext (ValuativeRel.valuation A).vle_iff_le.symm

/-- The range of `comap (mk 𝔞)` is `{ v ∈ Spv A | 𝔞 ≤ supp v }`. -/
lemma comap_quotient_range :
    Set.range (comap (Ideal.Quotient.mk 𝔞)) = { v : Spv A | 𝔞 ≤ v.supp } := by
  ext v
  simp only [Set.mem_range, Set.mem_setOf_eq]
  exact ⟨fun ⟨w, hw⟩ ↦ hw ▸ ideal_le_supp_comap_mk 𝔞 w,
    fun h ↦ ⟨quotientLift 𝔞 v h, comap_quotientLift 𝔞 v h⟩⟩

/-- `comap (mk 𝔞) : Spv (A ⧸ 𝔞) → Spv A` is a topological embedding. -/
lemma comap_quotient_isEmbedding :
    Topology.IsEmbedding (comap (Ideal.Quotient.mk 𝔞)) := by
  constructor
  · constructor
    change Spv.instTopologicalSpace =
      Spv.instTopologicalSpace.induced (comap (Ideal.Quotient.mk 𝔞))
    simp only [instTopologicalSpace, induced_generateFrom_eq]
    congr 1
    ext U
    simp only [Set.mem_setOf_eq, Set.mem_image]
    constructor
    · rintro ⟨f', s', rfl⟩
      obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective f'
      obtain ⟨s, rfl⟩ := Ideal.Quotient.mk_surjective s'
      exact ⟨basicOpen f s, ⟨f, s, rfl⟩, comap_preimage_basicOpen _ f s⟩
    · rintro ⟨_, ⟨f, s, rfl⟩, rfl⟩
      rw [comap_preimage_basicOpen]
      exact ⟨_, _, rfl⟩
  · exact comap_injective Ideal.Quotient.mk_surjective

end Quotient

/-! ### Localization — Remark 4.4(1) of Wedhorn

For a submonoid `S` of `A` and `B` a localization of `A` at `S`, the map
`Spv B → Spv A` induced by `algebraMap A B` has range
`{ v ∈ Spv A | S ≤ (supp v).primeCompl }`.
-/

section Localization

variable (S : Submonoid A) (B : Type*) [CommRing B] [Algebra A B] [IsLocalization S B]

/-- Lift a point `v ∈ Spv A` with `S ≤ (supp v).primeCompl` to `Spv B`,
where `B` is the localization of `A` at `S`. -/
noncomputable def localizationLift (v : Spv A) (hS : S ≤ v.supp.primeCompl) :
    Spv B :=
  have hS' : S ≤ (@ValuativeRel.valuation A _ v.toValuativeRel).supp.primeCompl := by
    intro s hs
    change s ∉ (@ValuativeRel.valuation A _ v.toValuativeRel).supp
    rw [← @ValuativeRel.supp_eq_valuation_supp A _ v.toValuativeRel]
    exact hS hs
  ofValuation ((@ValuativeRel.valuation A _ v.toValuativeRel).extendToLocalization hS' B)

/-- `comap (algebraMap A B) (localizationLift S B v hS) = v`. -/
lemma comap_localizationLift (v : Spv A) (hS : S ≤ v.supp.primeCompl) :
    comap (algebraMap A B) (localizationLift S B v hS) = v := by
  have hS' : S ≤ (@ValuativeRel.valuation A _ v.toValuativeRel).supp.primeCompl := by
    intro s hs; change s ∉ _
    rw [← @ValuativeRel.supp_eq_valuation_supp A _ v.toValuativeRel]; exact hS hs
  change comap (algebraMap A B)
    (ofValuation ((@ValuativeRel.valuation A _ v.toValuativeRel).extendToLocalization hS' B)) = v
  rw [comap_ofValuation,
    show ((@ValuativeRel.valuation A _ v.toValuativeRel).extendToLocalization hS' B).comap
      (algebraMap A B) = @ValuativeRel.valuation A _ v.toValuativeRel from
      Valuation.ext fun a => Valuation.extendToLocalization_apply_map_apply _ hS' B a]
  exact ofValuation_valuation v

end Localization

end Spv
