/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import «Adic spaces».LocalizationTopology
import Mathlib.Topology.Algebra.LinearTopology

/-!
# `IsLinearTopology` for `locTopology` (audit + minimal building block)

The single residual identified in `WedhornLocalizedTateData.lean`: the
`IsLinearTopology` instance for `(Localization.Away s, locTopology P T s
hopen)`, needed by `exists_dominating_unit_in_localization` (commit
`863aa86`).

## Audit

`locTopology` is generated by `locBasis`, a `RingSubgroupsBasis (locNhd
P T s)`. The basis sets `locNhd P T s n` are AddSubgroups of
`Localization.Away s`, NOT generally ideals: an element `d ∈ locNhd n`
is an image of `(locIdeal)^n ⊆ locSubring`, but `(1/s) · d` may exit
`locSubring` (since `1/s` is not generally in `locSubring`).

For `IsLinearTopology B B`, we need a basis of OPEN IDEALS at 0
(equivalently, open submodules of `B` over `B`). Two natural attempts:

1. Use `locNhd P T s n` directly: fails because `locNhd n` is not an
   ideal of `Localization.Away s`.

2. Use `Submodule.span (Localization.Away s) (locNhd n : Set _)` (the
   ideal of `B` generated by `locNhd n`): this IS an ideal, AND is
   open (contains the open `locNhd n` and contains `0`). This file
   proves openness as the building block.

   The remaining structural step: showing these spans form a BASIS at
   `0`, i.e., `∀ open U ∋ 0, ∃ n, Submodule.span B (locNhd n) ⊆ U`.
   This requires more delicate analysis since `Submodule.span B (locNhd
   n)` includes `B`-multiples of `locNhd n`, which can be larger than
   `locNhd n`. Whether the spans shrink fast enough to fit inside an
   arbitrary `locNhd m` is the genuine analytic content.

## What this file provides

`locNhd_span_isOpen` — `Submodule.span (Localization.Away s) (locNhd P T
s n : Set _)` is an open subset of `Localization.Away s` under
`locTopology P T s hopen`. Direct from
`AddSubgroup.isOpen_of_mem_nhds`-style argument: the span contains the
open `locNhd n`, so it's a neighborhood of `0`, hence open (additive
subgroup in topological group).

## Single residual

```lean
theorem isLinearTopology_locTopology
    {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s) :
    @IsLinearTopology (Localization.Away s) (Localization.Away s) _ _ _
      (locTopology P T s hopen)
```

The proof would use `IsLinearTopology.mk` with the explicit submodule
basis `fun n => Submodule.span (Localization.Away s) (locNhd P T s n)`,
provided that:
* For each `n`, this submodule is open and in `nhds 0` (provided by
  this file's `locNhd_span_isOpen`).
* For each `U ∈ nhds 0`, ∃ `n` with `Submodule.span B (locNhd n) ⊆ U`
  (the structural shrinking property — the genuinely missing piece).

The shrinking property requires a careful analysis of how `B`-spans of
`locNhd n` decrease in `n`. For typical Tate-Huber setups this should
hold, but it requires a non-trivial computation: for any open `U
⊇ locNhd m`, find `n` such that `B · locNhd n ⊆ locNhd m`. Equivalent
to: the `B`-action on `locNhd` is "tame" in the sense that finite
products with arbitrary `B`-elements eventually return to small
`locNhd`'s.

This is a structural-topological result on Wedhorn 8.1 localizations
and is the next concrete sub-target.

## Notes

* No root import; leaf-level file.
* No edits to committed bridge files or Secondary's
  per-branch-chain file.
* No Lane B / Cor 8.32 / Jacobson / T001 / faithful-flatness /
  final-acyclicity / T005 / T013 / T016 content. -/

namespace ValuationSpectrum

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- **Open-ideal containment for `locNhd` spans**.

For each `n`, the ideal `Submodule.span (Localization.Away s) (locNhd P
T s n : Set _)` is an open subset of `Localization.Away s` under
`locTopology P T s hopen`.

**Proof**: the submodule contains the open `locNhd n` (by
`Submodule.subset_span`), so it is a neighborhood of `0` in
`locTopology`. By `AddSubgroup.isOpen_of_mem_nhds` (via the underlying
add-group of the submodule), it is open as a set.

**Use case**: building block for the full `IsLinearTopology` theorem
(see file docblock). -/
theorem locNhd_span_isOpen
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s)
    (n : ℕ) :
    letI : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
    IsOpen ((Submodule.span (Localization.Away s)
      (locNhd P T s n : Set (Localization.Away s)) :
      Submodule (Localization.Away s) (Localization.Away s)) :
      Set (Localization.Away s)) := by
  letI : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
  haveI : IsTopologicalRing (Localization.Away s) :=
    (locBasis P T s hopen).toRingFilterBasis.isTopologicalRing
  -- The span is in nhds 0 since it contains the open locNhd n.
  have h_locNhd_open : IsOpen ((locNhd P T s n : Set (Localization.Away s))) := by
    have hmem : (locNhd P T s n : Set (Localization.Away s)) ∈
        @nhds _ (locTopology P T s hopen) 0 :=
      (locBasis P T s hopen).hasBasis_nhds_zero.mem_of_mem (i := n) trivial
    haveI : @IsTopologicalAddGroup _ (locTopology P T s hopen) _ :=
      @IsTopologicalRing.to_topologicalAddGroup _ _
        (locTopology P T s hopen)
        (locBasis P T s hopen).toRingFilterBasis.isTopologicalRing
    exact (locNhd P T s n).isOpen_of_mem_nhds hmem
  -- The span (as an AddSubgroup) is open since it contains the open locNhd n
  -- and is closed under addition + 0-containment.
  apply (Submodule.span (Localization.Away s)
    (locNhd P T s n : Set (Localization.Away s))).toAddSubgroup.isOpen_of_mem_nhds
    (g := 0)
  -- Need: ↑(span ...) ∈ nhds 0.
  refine Filter.mem_of_superset (h_locNhd_open.mem_nhds (locNhd P T s n).zero_mem) ?_
  intro x hx
  exact Submodule.subset_span hx

/-! ## Multiplication-taming step (per-element)

The `Submodule.span B (locNhd n)`-as-basis property requires for each
`m`, an `n` with `Submodule.span B (locNhd n) ⊆ locNhd m`. That `n`
must work UNIFORMLY across all `b ∈ B` (since the span is a B-module).

The available per-element multiplication-taming
(`locNhd_leftMul`, `Adic spaces/LocalizationTopology.lean:222`):
```
theorem locNhd_leftMul ... (x : Localization.Away s) (i : ℕ) :
    ∃ j, (locNhd P T s j : Set _) ⊆ (x * ·) ⁻¹' (locNhd P T s i : Set _)
```
gives `j_x` for each `x : B` and `i : ℕ`. But `j_x` depends on `x`, and
since `B = Localization.Away s` contains `1/s^k` for arbitrary `k : ℕ`,
the `j_x` is unbounded as `x` varies.

**Conclusion of audit**: the uniform multiplication-taming required for
`Submodule.span B (locNhd n) ⊆ locNhd m` does not follow from
`locNhd_leftMul` alone — that gives only per-element taming. A uniform
bound would require the topology to have additional structure (e.g.,
`Localization.Away s` being a Tate ring with a pseudo-uniformizer
absorbing all denominators).

## Single residual

The full uniform-multiplication-taming theorem:

```lean
theorem locNhd_span_subset_locNhd
    {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s)
    -- Likely needs: a Tate-ring / pseudo-uniformizer hypothesis on
    -- `(Localization.Away s, locTopology P T s hopen)` to bound the
    -- denominator-power growth uniformly.
    (m : ℕ) :
    ∃ n : ℕ,
      ((Submodule.span (Localization.Away s)
        (locNhd P T s n : Set (Localization.Away s))) :
        Set (Localization.Away s)) ⊆
        (locNhd P T s m : Set (Localization.Away s))
```

**Proof obstruction**: take `b = 1/s^k ∈ B`. For `b · y ∈ locNhd m`
with `y ∈ locNhd n`: need `(1/s)^k · y ∈ locNhd m`. This requires `y`
to have at least `k * N + m` `P.I`-content (where N is from `hopen`).
For uniform `n` over all `k`, no such `n` exists. The theorem requires
either:

* An additional hypothesis bounding the denominator powers (e.g., via
  a topologically-nilpotent unit absorbing `1/s`), OR
* A structural theorem that `locTopology` is the Huber topology on
  `(Localization.Away s, locSubring, locIdeal)`, which has a known
  linear topology characterization (probably via Mathlib's existing
  Huber-ring API).

Either route is genuinely deeper than the smaller multiplication-taming
target the manager outlined; this audit identifies the precise reason
the smaller form does not directly close `IsLinearTopology` for
`locTopology`.

## Smaller building block (per-element multiplication-taming)

Already exists in Mathlib via `RingFilterBasis.toAddGroupFilterBasis`
plus the `RingSubgroupsBasis` infrastructure used by `locBasis`. The
gap is specifically the UNIFORM uplift to `Submodule.span B`.

-/

end ValuationSpectrum
