/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import «Adic spaces».LocalizationTopology
import Mathlib.Topology.Algebra.LinearTopology

/-!
# `IsLinearTopology` for `locTopology` (audit + minimal building block)

The single residual identified in `WedhornLocalizedTateData.lean`: the
`IsLinearTopology` instance for `(Localization.Away s, locTopology P T s
hopen)`, needed by `exists_dominating_unit_in_localization` (commit
`863aa86`).

## Audit

`locTopology` is generated by `locBasis`, a `RingSubgroupsBasis (locNhd
P T s)`. The basis sets `locNhd P T s n` are AddSubgroups of
`Localization.Away s`, NOT generally ideals: an element `d ∈ locNhd n`
is an image of `(locIdeal)^n ⊆ locSubring`, but `(1/s) · d` may exit
`locSubring` (since `1/s` is not generally in `locSubring`).

For `IsLinearTopology B B`, we need a basis of OPEN IDEALS at 0
(equivalently, open submodules of `B` over `B`). Two natural attempts:

1. Use `locNhd P T s n` directly: fails because `locNhd n` is not an
   ideal of `Localization.Away s`.

2. Use `Submodule.span (Localization.Away s) (locNhd n : Set _)` (the
   ideal of `B` generated by `locNhd n`): this IS an ideal, AND is
   open (contains the open `locNhd n` and contains `0`). This file
   proves openness as the building block.

   The remaining structural step: showing these spans form a BASIS at
   `0`, i.e., `∀ open U ∋ 0, ∃ n, Submodule.span B (locNhd n) ⊆ U`.
   This requires more delicate analysis since `Submodule.span B (locNhd
   n)` includes `B`-multiples of `locNhd n`, which can be larger than
   `locNhd n`. Whether the spans shrink fast enough to fit inside an
   arbitrary `locNhd m` is the genuine analytic content.

## What this file provides

`locNhd_span_isOpen` — `Submodule.span (Localization.Away s) (locNhd P T
s n : Set _)` is an open subset of `Localization.Away s` under
`locTopology P T s hopen`. Direct from
`AddSubgroup.isOpen_of_mem_nhds`-style argument: the span contains the
open `locNhd n`, so it's a neighborhood of `0`, hence open (additive
subgroup in topological group).

## Single residual

```lean
theorem isLinearTopology_locTopology
    {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s) :
    @IsLinearTopology (Localization.Away s) (Localization.Away s) _ _ _
      (locTopology P T s hopen)
```

The proof would use `IsLinearTopology.mk` with the explicit submodule
basis `fun n => Submodule.span (Localization.Away s) (locNhd P T s n)`,
provided that:
* For each `n`, this submodule is open and in `nhds 0` (provided by
  this file's `locNhd_span_isOpen`).
* For each `U ∈ nhds 0`, ∃ `n` with `Submodule.span B (locNhd n) ⊆ U`
  (the structural shrinking property — the genuinely missing piece).

The shrinking property requires a careful analysis of how `B`-spans of
`locNhd n` decrease in `n`. For typical Tate-Huber setups this should
hold, but it requires a non-trivial computation: for any open `U
⊇ locNhd m`, find `n` such that `B · locNhd n ⊆ locNhd m`. Equivalent
to: the `B`-action on `locNhd` is "tame" in the sense that finite
products with arbitrary `B`-elements eventually return to small
`locNhd`'s.

This is a structural-topological result on Wedhorn 8.1 localizations
and is the next concrete sub-target.

## Notes

* No root import; leaf-level file.
* No edits to committed bridge files or Secondary's
  per-branch-chain file.
* No Lane B / Cor 8.32 / Jacobson / T001 / faithful-flatness /
  final-acyclicity / T005 / T013 / T016 content. -/

open Pointwise

namespace ValuationSpectrum

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- **Open-ideal containment for `locNhd` spans**.

For each `n`, the ideal `Submodule.span (Localization.Away s) (locNhd P
T s n : Set _)` is an open subset of `Localization.Away s` under
`locTopology P T s hopen`.

**Proof**: the submodule contains the open `locNhd n` (by
`Submodule.subset_span`), so it is a neighborhood of `0` in
`locTopology`. By `AddSubgroup.isOpen_of_mem_nhds` (via the underlying
add-group of the submodule), it is open as a set.

**Use case**: building block for the full `IsLinearTopology` theorem
(see file docblock). -/
theorem locNhd_span_isOpen
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s)
    (n : ℕ) :
    letI : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
    IsOpen ((Submodule.span (Localization.Away s)
      (locNhd P T s n : Set (Localization.Away s)) :
      Submodule (Localization.Away s) (Localization.Away s)) :
      Set (Localization.Away s)) := by
  letI : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
  haveI : IsTopologicalRing (Localization.Away s) :=
    (locBasis P T s hopen).toRingFilterBasis.isTopologicalRing
  -- The span is in nhds 0 since it contains the open locNhd n.
  have h_locNhd_open : IsOpen ((locNhd P T s n : Set (Localization.Away s))) := by
    have hmem : (locNhd P T s n : Set (Localization.Away s)) ∈
        @nhds _ (locTopology P T s hopen) 0 :=
      (locBasis P T s hopen).hasBasis_nhds_zero.mem_of_mem (i := n) trivial
    haveI : @IsTopologicalAddGroup _ (locTopology P T s hopen) _ :=
      @IsTopologicalRing.to_topologicalAddGroup _ _
        (locTopology P T s hopen)
        (locBasis P T s hopen).toRingFilterBasis.isTopologicalRing
    exact (locNhd P T s n).isOpen_of_mem_nhds hmem
  -- The span (as an AddSubgroup) is open since it contains the open locNhd n
  -- and is closed under addition + 0-containment.
  apply (Submodule.span (Localization.Away s)
    (locNhd P T s n : Set (Localization.Away s))).toAddSubgroup.isOpen_of_mem_nhds
    (g := 0)
  -- Need: ↑(span ...) ∈ nhds 0.
  refine Filter.mem_of_superset (h_locNhd_open.mem_nhds (locNhd P T s n).zero_mem) ?_
  intro x hx
  exact Submodule.subset_span hx

/-! ## Multiplication-taming step (per-element)

The `Submodule.span B (locNhd n)`-as-basis property requires for each
`m`, an `n` with `Submodule.span B (locNhd n) ⊆ locNhd m`. That `n`
must work UNIFORMLY across all `b ∈ B` (since the span is a B-module).

The available per-element multiplication-taming
(`locNhd_leftMul`, `Adic spaces/LocalizationTopology.lean:222`):
```
theorem locNhd_leftMul ... (x : Localization.Away s) (i : ℕ) :
    ∃ j, (locNhd P T s j : Set _) ⊆ (x * ·) ⁻¹' (locNhd P T s i : Set _)
```
gives `j_x` for each `x : B` and `i : ℕ`. But `j_x` depends on `x`, and
since `B = Localization.Away s` contains `1/s^k` for arbitrary `k : ℕ`,
the `j_x` is unbounded as `x` varies.

**Conclusion of audit**: the uniform multiplication-taming required for
`Submodule.span B (locNhd n) ⊆ locNhd m` does not follow from
`locNhd_leftMul` alone — that gives only per-element taming. A uniform
bound would require the topology to have additional structure (e.g.,
`Localization.Away s` being a Tate ring with a pseudo-uniformizer
absorbing all denominators).

## Single residual

The full uniform-multiplication-taming theorem:

```lean
theorem locNhd_span_subset_locNhd
    {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s)
    -- Likely needs: a Tate-ring / pseudo-uniformizer hypothesis on
    -- `(Localization.Away s, locTopology P T s hopen)` to bound the
    -- denominator-power growth uniformly.
    (m : ℕ) :
    ∃ n : ℕ,
      ((Submodule.span (Localization.Away s)
        (locNhd P T s n : Set (Localization.Away s))) :
        Set (Localization.Away s)) ⊆
        (locNhd P T s m : Set (Localization.Away s))
```

**Proof obstruction**: take `b = 1/s^k ∈ B`. For `b · y ∈ locNhd m`
with `y ∈ locNhd n`: need `(1/s)^k · y ∈ locNhd m`. This requires `y`
to have at least `k * N + m` `P.I`-content (where N is from `hopen`).
For uniform `n` over all `k`, no such `n` exists. The theorem requires
either:

* An additional hypothesis bounding the denominator powers (e.g., via
  a topologically-nilpotent unit absorbing `1/s`), OR
* A structural theorem that `locTopology` is the Huber topology on
  `(Localization.Away s, locSubring, locIdeal)`, which has a known
  linear topology characterization (probably via Mathlib's existing
  Huber-ring API).

Either route is genuinely deeper than the smaller multiplication-taming
target the manager outlined; this audit identifies the precise reason
the smaller form does not directly close `IsLinearTopology` for
`locTopology`.

## Smaller building block (per-element multiplication-taming)

Already exists in Mathlib via `RingFilterBasis.toAddGroupFilterBasis`
plus the `RingSubgroupsBasis` infrastructure used by `locBasis`. The
gap is specifically the UNIFORM uplift to `Submodule.span B`.

-/

/-! ## `locNhd` / `locIdeal` power API for Artin-Rees consumers (T090)

Reusable structural API supporting Artin-Rees-style proofs that need to
move between `locNhd P T s n` (additive subgroups of `Localization.Away s`),
`locIdeal P T s ^ n` (ideals of `locSubring P T s`), and the source-side
`P.I ^ n` (ideals of `P.A₀`). The basis-indexed residual exposed by
`locLift_open_on_image_at_zero_of_basis_form`
(`Adic spaces/PresheafTateStructure.lean:1563`) consumes precisely this
shape: it asks for `n ↦ m` such that elements `a` with
`locLift a ∈ locNhd D m` admit a representative `b ∈ locNhd D₀ n` with
the same `locLift` image. The structural API here lets the consumer
case-split, lift, and rebalance without re-deriving the basic
membership/closure facts.

The single substantive theorem is `locNhd_eq_locSubring_image_PI_pow`,
which states exactly: `locNhd P T s n` is the additive subgroup generated
by `locSubring P T s`-multiples of `algebraMap A (Localization.Away s)`
applied to `P.I ^ n` elements (lifted via `Subtype.val : P.A₀ → A`). The
ancillary corollaries package the four primitive shapes the consumer
needs:

* `mem_locNhd_iff` — clean iff form (subtype image of `locIdeal^n`).
* `algebraMap_PI_pow_mem_locNhd` — base elements (`algebraMap` of
  `P.I^n` elements lies in `locNhd n`).
* `locNhd_locSubring_smul_mem` — module property over `locSubring`
  (closure under multiplication by `(d : Loc)` for `d ∈ locSubring`).
* `locNhd_mul_subset` — multiplicative shift `locNhd n · locNhd m ⊆
  locNhd (n+m)`.
-/

omit [IsTopologicalRing A] in
/-- **`locNhd` membership iff form** (T090 reusable primitive).

Direct iff-form of the `locNhd P T s n` definition: an element
`y : Localization.Away s` lies in `locNhd P T s n` iff there exists
`d : locSubring P T s` with `d ∈ locIdeal P T s ^ n` and `(d : Localization.Away s) = y`.

Reusable for case analysis in Artin-Rees consumers needing to extract
the `locSubring`-witness `d`. -/
theorem mem_locNhd_iff
    (P : PairOfDefinition A) (T : Finset A) (s : A) (n : ℕ)
    (y : Localization.Away s) :
    y ∈ locNhd P T s n ↔
      ∃ d : locSubring P T s,
        d ∈ (locIdeal P T s) ^ n ∧ (d : Localization.Away s) = y :=
  Iff.rfl

omit [IsTopologicalRing A] in
/-- **`locIdeal` power as `Ideal.map` of `P.I^n`** (T090 reusable
primitive).

The `n`-th power of the ideal of definition equals the `algebraMapD`-
image of the `n`-th power of `P.I`:
`(locIdeal P T s)^n = Ideal.map (algebraMapD P T s) (P.I^n)`.

Direct from `Ideal.map_pow`. Useful in Artin-Rees arguments where one
needs to relate the `P.I`-adic filtration on `P.A₀` to the `locIdeal`-
adic filtration on `locSubring`. -/
theorem locIdeal_pow_eq
    (P : PairOfDefinition A) (T : Finset A) (s : A) (n : ℕ) :
    (locIdeal P T s) ^ n = Ideal.map (algebraMapD P T s) (P.I ^ n) := by
  unfold locIdeal
  rw [← Ideal.map_pow]

omit [IsTopologicalRing A] in
/-- **`algebraMap` of `P.I^n` elements lies in `locNhd n`** (T090
reusable primitive).

For any `b : P.A₀` with `b ∈ P.I^n`, the image
`algebraMap A (Localization.Away s) (b : A)` lies in `locNhd P T s n`.

This is the source-side base case for the Artin-Rees consumer: it shows
that elements arising directly from `P.I^n` (via `algebraMap`) are
members of the `n`-th `locNhd`. The witness in `locSubring` is
`algebraMapD P T s b`. -/
theorem algebraMap_PI_pow_mem_locNhd
    (P : PairOfDefinition A) (T : Finset A) (s : A) (n : ℕ)
    (b : P.A₀) (hb : b ∈ P.I ^ n) :
    algebraMap A (Localization.Away s) (b : A) ∈ locNhd P T s n := by
  refine ⟨algebraMapD P T s b, ?_, rfl⟩
  rw [locIdeal_pow_eq]
  exact Ideal.mem_map_of_mem _ hb

omit [IsTopologicalRing A] in
/-- **`locNhd` is closed under `locSubring`-multiplication** (T090
reusable primitive — module property).

For any `d : locSubring P T s` and `y ∈ locNhd P T s n`, the product
`(d : Localization.Away s) * y` lies in `locNhd P T s n`. Equivalently,
`locNhd P T s n` is a `locSubring P T s`-submodule of
`Localization.Away s`.

**Mathematical content**: `locIdeal P T s ^ n` is an ideal of
`locSubring P T s`, hence stable under `locSubring`-multiplication.
Pushing through `subtype` to `Localization.Away s` preserves this
stability since `subtype` is a ring homomorphism. -/
theorem locNhd_locSubring_smul_mem
    (P : PairOfDefinition A) (T : Finset A) (s : A) (n : ℕ)
    (d : locSubring P T s) {y : Localization.Away s}
    (hy : y ∈ locNhd P T s n) :
    (d : Localization.Away s) * y ∈ locNhd P T s n := by
  obtain ⟨e, he, rfl⟩ := hy
  exact ⟨d * e, Ideal.mul_mem_left _ d he, MulMemClass.coe_mul ..⟩

omit [IsTopologicalRing A] in
/-- **Multiplicative shift `locNhd n * locNhd m ⊆ locNhd (n+m)`** (T090
strong general theorem).

For any `n, m : ℕ`, the pointwise product
`(locNhd P T s n : Set _) * (locNhd P T s m : Set _)` is contained in
`(locNhd P T s (n + m) : Set _)`.

**Mathematical content**: this is the natural multiplicative behaviour
of an ideal-power filtration. For `y₁ = (d₁ : Loc)` with `d₁ ∈
locIdeal^n` and `y₂ = (d₂ : Loc)` with `d₂ ∈ locIdeal^m`, the product
`y₁ * y₂ = (d₁ * d₂ : Loc)` with `d₁ * d₂ ∈ locIdeal^n * locIdeal^m
⊆ locIdeal^(n+m)` (via `Ideal.mul_mem_mul` + `pow_add`).

**Use case**: Artin-Rees and denominator-clearing arguments use this
to absorb factors at appropriate filtration levels. Combined with the
`locSubring`-module property, this gives a complete multiplicative API
for `locNhd`-power calculations. -/
theorem locNhd_mul_subset
    (P : PairOfDefinition A) (T : Finset A) (s : A) (n m : ℕ) :
    (locNhd P T s n : Set (Localization.Away s)) *
        (locNhd P T s m : Set (Localization.Away s)) ⊆
      (locNhd P T s (n + m) : Set (Localization.Away s)) := by
  rintro _ ⟨_, ⟨d₁, hd₁, rfl⟩, _, ⟨d₂, hd₂, rfl⟩, rfl⟩
  refine ⟨d₁ * d₂, ?_, MulMemClass.coe_mul ..⟩
  rw [pow_add]
  exact Ideal.mul_mem_mul hd₁ hd₂

omit [IsTopologicalRing A] in
/-- **Subtype image characterisation of `locNhd`** (T090 reusable
primitive — set-level form).

`locNhd P T s n` (as a `Set`) is exactly the image of
`(locIdeal P T s)^n` under the subtype embedding
`(locSubring P T s).subtype : locSubring P T s → Localization.Away s`.

Set-level packaging of `mem_locNhd_iff`, useful when one needs to
manipulate `locNhd` as a subset of `Localization.Away s` rather than
as an `AddSubgroup`. The image is well-defined since `locIdeal^n` is
an `AddSubgroup` of `locSubring P T s` and the subtype is an
additive monoid hom. -/
theorem locNhd_eq_subtype_image
    (P : PairOfDefinition A) (T : Finset A) (s : A) (n : ℕ) :
    (locNhd P T s n : Set (Localization.Away s)) =
      (locSubring P T s).subtype ''
        (((locIdeal P T s) ^ n : Ideal (locSubring P T s)) :
          Set (locSubring P T s)) := by
  ext y
  exact ⟨fun ⟨d, hd, heq⟩ => ⟨d, hd, heq⟩, fun ⟨d, hd, heq⟩ => ⟨d, hd, heq⟩⟩

end ValuationSpectrum
