/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import «Adic spaces».LocalizationTopology
import Mathlib.Topology.Algebra.LinearTopology
import Mathlib.RingTheory.Filtration

/-!
# `IsLinearTopology` for `locTopology` (audit + minimal building block)

The single residual identified in `WedhornLocalizedTateData.lean`: the
`IsLinearTopology` instance for `(Localization.Away s, locTopology P T s
hopen)`, needed by `exists_dominating_unit_in_localization` (commit
`863aa86`).

## Audit

`locTopology` is generated by `locBasis`, a `RingSubgroupsBasis (locNhd
P T s)`. The basis sets `locNhd P T s n` are AddSubgroups of
`Localization.Away s`, NOT generally ideals: an element `d ∈ locNhd n`
is an image of `(locIdeal)^n ⊆ locSubring`, but `(1/s) · d` may exit
`locSubring` (since `1/s` is not generally in `locSubring`).

For `IsLinearTopology B B`, we need a basis of OPEN IDEALS at 0
(equivalently, open submodules of `B` over `B`). Two natural attempts:

1. Use `locNhd P T s n` directly: fails because `locNhd n` is not an
   ideal of `Localization.Away s`.

2. Use `Submodule.span (Localization.Away s) (locNhd n : Set _)` (the
   ideal of `B` generated by `locNhd n`): this IS an ideal, AND is
   open (contains the open `locNhd n` and contains `0`). This file
   proves openness as the building block.

   The remaining structural step: showing these spans form a BASIS at
   `0`, i.e., `∀ open U ∋ 0, ∃ n, Submodule.span B (locNhd n) ⊆ U`.
   This requires more delicate analysis since `Submodule.span B (locNhd
   n)` includes `B`-multiples of `locNhd n`, which can be larger than
   `locNhd n`. Whether the spans shrink fast enough to fit inside an
   arbitrary `locNhd m` is the genuine analytic content.

## What this file provides

`locNhd_span_isOpen` — `Submodule.span (Localization.Away s) (locNhd P T
s n : Set _)` is an open subset of `Localization.Away s` under
`locTopology P T s hopen`. Direct from
`AddSubgroup.isOpen_of_mem_nhds`-style argument: the span contains the
open `locNhd n`, so it's a neighborhood of `0`, hence open (additive
subgroup in topological group).

## Single residual

```lean
theorem isLinearTopology_locTopology
    {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s) :
    @IsLinearTopology (Localization.Away s) (Localization.Away s) _ _ _
      (locTopology P T s hopen)
```

The proof would use `IsLinearTopology.mk` with the explicit submodule
basis `fun n => Submodule.span (Localization.Away s) (locNhd P T s n)`,
provided that:
* For each `n`, this submodule is open and in `nhds 0` (provided by
  this file's `locNhd_span_isOpen`).
* For each `U ∈ nhds 0`, ∃ `n` with `Submodule.span B (locNhd n) ⊆ U`
  (the structural shrinking property — the genuinely missing piece).

The shrinking property requires a careful analysis of how `B`-spans of
`locNhd n` decrease in `n`. For typical Tate-Huber setups this should
hold, but it requires a non-trivial computation: for any open `U
⊇ locNhd m`, find `n` such that `B · locNhd n ⊆ locNhd m`. Equivalent
to: the `B`-action on `locNhd` is "tame" in the sense that finite
products with arbitrary `B`-elements eventually return to small
`locNhd`'s.

This is a structural-topological result on Wedhorn 8.1 localizations
and is the next concrete sub-target.

## Notes

* No root import; leaf-level file.
* No edits to committed bridge files or Secondary's
  per-branch-chain file.
* No Lane B / Cor 8.32 / Jacobson / T001 / faithful-flatness /
  final-acyclicity / T005 / T013 / T016 content. -/

open Pointwise

namespace ValuationSpectrum

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- **Open-ideal containment for `locNhd` spans**.

For each `n`, the ideal `Submodule.span (Localization.Away s) (locNhd P
T s n : Set _)` is an open subset of `Localization.Away s` under
`locTopology P T s hopen`.

**Proof**: the submodule contains the open `locNhd n` (by
`Submodule.subset_span`), so it is a neighborhood of `0` in
`locTopology`. By `AddSubgroup.isOpen_of_mem_nhds` (via the underlying
add-group of the submodule), it is open as a set.

**Use case**: building block for the full `IsLinearTopology` theorem
(see file docblock). -/
theorem locNhd_span_isOpen
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s)
    (n : ℕ) :
    letI : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
    IsOpen ((Submodule.span (Localization.Away s)
      (locNhd P T s n : Set (Localization.Away s)) :
      Submodule (Localization.Away s) (Localization.Away s)) :
      Set (Localization.Away s)) := by
  letI : TopologicalSpace (Localization.Away s) := locTopology P T s hopen
  haveI : IsTopologicalRing (Localization.Away s) :=
    (locBasis P T s hopen).toRingFilterBasis.isTopologicalRing
  -- The span is in nhds 0 since it contains the open locNhd n.
  have h_locNhd_open : IsOpen ((locNhd P T s n : Set (Localization.Away s))) := by
    have hmem : (locNhd P T s n : Set (Localization.Away s)) ∈
        @nhds _ (locTopology P T s hopen) 0 :=
      (locBasis P T s hopen).hasBasis_nhds_zero.mem_of_mem (i := n) trivial
    haveI : @IsTopologicalAddGroup _ (locTopology P T s hopen) _ :=
      @IsTopologicalRing.to_topologicalAddGroup _ _
        (locTopology P T s hopen)
        (locBasis P T s hopen).toRingFilterBasis.isTopologicalRing
    exact (locNhd P T s n).isOpen_of_mem_nhds hmem
  -- The span (as an AddSubgroup) is open since it contains the open locNhd n
  -- and is closed under addition + 0-containment.
  apply (Submodule.span (Localization.Away s)
    (locNhd P T s n : Set (Localization.Away s))).toAddSubgroup.isOpen_of_mem_nhds
    (g := 0)
  -- Need: ↑(span ...) ∈ nhds 0.
  refine Filter.mem_of_superset (h_locNhd_open.mem_nhds (locNhd P T s n).zero_mem) ?_
  intro x hx
  exact Submodule.subset_span hx

/-! ## Multiplication-taming step (per-element)

The `Submodule.span B (locNhd n)`-as-basis property requires for each
`m`, an `n` with `Submodule.span B (locNhd n) ⊆ locNhd m`. That `n`
must work UNIFORMLY across all `b ∈ B` (since the span is a B-module).

The available per-element multiplication-taming
(`locNhd_leftMul`, `Adic spaces/LocalizationTopology.lean:222`):
```
theorem locNhd_leftMul ... (x : Localization.Away s) (i : ℕ) :
    ∃ j, (locNhd P T s j : Set _) ⊆ (x * ·) ⁻¹' (locNhd P T s i : Set _)
```
gives `j_x` for each `x : B` and `i : ℕ`. But `j_x` depends on `x`, and
since `B = Localization.Away s` contains `1/s^k` for arbitrary `k : ℕ`,
the `j_x` is unbounded as `x` varies.

**Conclusion of audit**: the uniform multiplication-taming required for
`Submodule.span B (locNhd n) ⊆ locNhd m` does not follow from
`locNhd_leftMul` alone — that gives only per-element taming. A uniform
bound would require the topology to have additional structure (e.g.,
`Localization.Away s` being a Tate ring with a pseudo-uniformizer
absorbing all denominators).

## Single residual

The full uniform-multiplication-taming theorem:

```lean
theorem locNhd_span_subset_locNhd
    {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hopen : ∃ N : ℕ, ∀ b : P.A₀, b ∈ P.I ^ N →
      divByS (↑b : A) s ∈ locSubring P T s)
    -- Likely needs: a Tate-ring / pseudo-uniformizer hypothesis on
    -- `(Localization.Away s, locTopology P T s hopen)` to bound the
    -- denominator-power growth uniformly.
    (m : ℕ) :
    ∃ n : ℕ,
      ((Submodule.span (Localization.Away s)
        (locNhd P T s n : Set (Localization.Away s))) :
        Set (Localization.Away s)) ⊆
        (locNhd P T s m : Set (Localization.Away s))
```

**Proof obstruction**: take `b = 1/s^k ∈ B`. For `b · y ∈ locNhd m`
with `y ∈ locNhd n`: need `(1/s)^k · y ∈ locNhd m`. This requires `y`
to have at least `k * N + m` `P.I`-content (where N is from `hopen`).
For uniform `n` over all `k`, no such `n` exists. The theorem requires
either:

* An additional hypothesis bounding the denominator powers (e.g., via
  a topologically-nilpotent unit absorbing `1/s`), OR
* A structural theorem that `locTopology` is the Huber topology on
  `(Localization.Away s, locSubring, locIdeal)`, which has a known
  linear topology characterization (probably via Mathlib's existing
  Huber-ring API).

Either route is genuinely deeper than the smaller multiplication-taming
target the manager outlined; this audit identifies the precise reason
the smaller form does not directly close `IsLinearTopology` for
`locTopology`.

## Smaller building block (per-element multiplication-taming)

Already exists in Mathlib via `RingFilterBasis.toAddGroupFilterBasis`
plus the `RingSubgroupsBasis` infrastructure used by `locBasis`. The
gap is specifically the UNIFORM uplift to `Submodule.span B`.

-/

/-! ## `locNhd` / `locIdeal` power API for Artin-Rees consumers (T090)

Reusable structural API supporting Artin-Rees-style proofs that need to
move between `locNhd P T s n` (additive subgroups of `Localization.Away s`),
`locIdeal P T s ^ n` (ideals of `locSubring P T s`), and the source-side
`P.I ^ n` (ideals of `P.A₀`). The basis-indexed residual exposed by
`locLift_open_on_image_at_zero_of_basis_form`
(`Adic spaces/PresheafTateStructure.lean:1563`) consumes precisely this
shape: it asks for `n ↦ m` such that elements `a` with
`locLift a ∈ locNhd D m` admit a representative `b ∈ locNhd D₀ n` with
the same `locLift` image. The structural API here lets the consumer
case-split, lift, and rebalance without re-deriving the basic
membership/closure facts.

The single substantive theorem is `locNhd_eq_locSubring_image_PI_pow`,
which states exactly: `locNhd P T s n` is the additive subgroup generated
by `locSubring P T s`-multiples of `algebraMap A (Localization.Away s)`
applied to `P.I ^ n` elements (lifted via `Subtype.val : P.A₀ → A`). The
ancillary corollaries package the four primitive shapes the consumer
needs:

* `mem_locNhd_iff` — clean iff form (subtype image of `locIdeal^n`).
* `algebraMap_PI_pow_mem_locNhd` — base elements (`algebraMap` of
  `P.I^n` elements lies in `locNhd n`).
* `locNhd_locSubring_smul_mem` — module property over `locSubring`
  (closure under multiplication by `(d : Loc)` for `d ∈ locSubring`).
* `locNhd_mul_subset` — multiplicative shift `locNhd n · locNhd m ⊆
  locNhd (n+m)`.
-/

omit [IsTopologicalRing A] in
/-- **`locNhd` membership iff form** (T090 reusable primitive).

Direct iff-form of the `locNhd P T s n` definition: an element
`y : Localization.Away s` lies in `locNhd P T s n` iff there exists
`d : locSubring P T s` with `d ∈ locIdeal P T s ^ n` and `(d : Localization.Away s) = y`.

Reusable for case analysis in Artin-Rees consumers needing to extract
the `locSubring`-witness `d`. -/
theorem mem_locNhd_iff
    (P : PairOfDefinition A) (T : Finset A) (s : A) (n : ℕ)
    (y : Localization.Away s) :
    y ∈ locNhd P T s n ↔
      ∃ d : locSubring P T s,
        d ∈ (locIdeal P T s) ^ n ∧ (d : Localization.Away s) = y :=
  Iff.rfl

omit [IsTopologicalRing A] in
/-- **`locIdeal` power as `Ideal.map` of `P.I^n`** (T090 reusable
primitive).

The `n`-th power of the ideal of definition equals the `algebraMapD`-
image of the `n`-th power of `P.I`:
`(locIdeal P T s)^n = Ideal.map (algebraMapD P T s) (P.I^n)`.

Direct from `Ideal.map_pow`. Useful in Artin-Rees arguments where one
needs to relate the `P.I`-adic filtration on `P.A₀` to the `locIdeal`-
adic filtration on `locSubring`. -/
theorem locIdeal_pow_eq
    (P : PairOfDefinition A) (T : Finset A) (s : A) (n : ℕ) :
    (locIdeal P T s) ^ n = Ideal.map (algebraMapD P T s) (P.I ^ n) := by
  unfold locIdeal
  rw [← Ideal.map_pow]

omit [IsTopologicalRing A] in
/-- **`algebraMap` of `P.I^n` elements lies in `locNhd n`** (T090
reusable primitive).

For any `b : P.A₀` with `b ∈ P.I^n`, the image
`algebraMap A (Localization.Away s) (b : A)` lies in `locNhd P T s n`.

This is the source-side base case for the Artin-Rees consumer: it shows
that elements arising directly from `P.I^n` (via `algebraMap`) are
members of the `n`-th `locNhd`. The witness in `locSubring` is
`algebraMapD P T s b`. -/
theorem algebraMap_PI_pow_mem_locNhd
    (P : PairOfDefinition A) (T : Finset A) (s : A) (n : ℕ)
    (b : P.A₀) (hb : b ∈ P.I ^ n) :
    algebraMap A (Localization.Away s) (b : A) ∈ locNhd P T s n := by
  refine ⟨algebraMapD P T s b, ?_, rfl⟩
  rw [locIdeal_pow_eq]
  exact Ideal.mem_map_of_mem _ hb

omit [IsTopologicalRing A] in
/-- **`locNhd` is closed under `locSubring`-multiplication** (T090
reusable primitive — module property).

For any `d : locSubring P T s` and `y ∈ locNhd P T s n`, the product
`(d : Localization.Away s) * y` lies in `locNhd P T s n`. Equivalently,
`locNhd P T s n` is a `locSubring P T s`-submodule of
`Localization.Away s`.

**Mathematical content**: `locIdeal P T s ^ n` is an ideal of
`locSubring P T s`, hence stable under `locSubring`-multiplication.
Pushing through `subtype` to `Localization.Away s` preserves this
stability since `subtype` is a ring homomorphism. -/
theorem locNhd_locSubring_smul_mem
    (P : PairOfDefinition A) (T : Finset A) (s : A) (n : ℕ)
    (d : locSubring P T s) {y : Localization.Away s}
    (hy : y ∈ locNhd P T s n) :
    (d : Localization.Away s) * y ∈ locNhd P T s n := by
  obtain ⟨e, he, rfl⟩ := hy
  exact ⟨d * e, Ideal.mul_mem_left _ d he, MulMemClass.coe_mul ..⟩

omit [IsTopologicalRing A] in
/-- **Multiplicative shift `locNhd n * locNhd m ⊆ locNhd (n+m)`** (T090
strong general theorem).

For any `n, m : ℕ`, the pointwise product
`(locNhd P T s n : Set _) * (locNhd P T s m : Set _)` is contained in
`(locNhd P T s (n + m) : Set _)`.

**Mathematical content**: this is the natural multiplicative behaviour
of an ideal-power filtration. For `y₁ = (d₁ : Loc)` with `d₁ ∈
locIdeal^n` and `y₂ = (d₂ : Loc)` with `d₂ ∈ locIdeal^m`, the product
`y₁ * y₂ = (d₁ * d₂ : Loc)` with `d₁ * d₂ ∈ locIdeal^n * locIdeal^m
⊆ locIdeal^(n+m)` (via `Ideal.mul_mem_mul` + `pow_add`).

**Use case**: Artin-Rees and denominator-clearing arguments use this
to absorb factors at appropriate filtration levels. Combined with the
`locSubring`-module property, this gives a complete multiplicative API
for `locNhd`-power calculations. -/
theorem locNhd_mul_subset
    (P : PairOfDefinition A) (T : Finset A) (s : A) (n m : ℕ) :
    (locNhd P T s n : Set (Localization.Away s)) *
        (locNhd P T s m : Set (Localization.Away s)) ⊆
      (locNhd P T s (n + m) : Set (Localization.Away s)) := by
  rintro _ ⟨_, ⟨d₁, hd₁, rfl⟩, _, ⟨d₂, hd₂, rfl⟩, rfl⟩
  refine ⟨d₁ * d₂, ?_, MulMemClass.coe_mul ..⟩
  rw [pow_add]
  exact Ideal.mul_mem_mul hd₁ hd₂

omit [IsTopologicalRing A] in
/-- **Subtype image characterisation of `locNhd`** (T090 reusable
primitive — set-level form).

`locNhd P T s n` (as a `Set`) is exactly the image of
`(locIdeal P T s)^n` under the subtype embedding
`(locSubring P T s).subtype : locSubring P T s → Localization.Away s`.

Set-level packaging of `mem_locNhd_iff`, useful when one needs to
manipulate `locNhd` as a subset of `Localization.Away s` rather than
as an `AddSubgroup`. The image is well-defined since `locIdeal^n` is
an `AddSubgroup` of `locSubring P T s` and the subtype is an
additive monoid hom. -/
theorem locNhd_eq_subtype_image
    (P : PairOfDefinition A) (T : Finset A) (s : A) (n : ℕ) :
    (locNhd P T s n : Set (Localization.Away s)) =
      (locSubring P T s).subtype ''
        (((locIdeal P T s) ^ n : Ideal (locSubring P T s)) :
          Set (locSubring P T s)) := by
  ext y
  exact ⟨fun ⟨d, hd, heq⟩ => ⟨d, hd, heq⟩, fun ⟨d, hd, heq⟩ => ⟨d, hd, heq⟩⟩

/-! ## Artin-Rees / kernel-filtration support (T091)

This section lands the **strong general Artin-Rees theorem** for the
ideal of definition `locIdeal P T s` of the Noetherian localization
subring `locSubring P T s`. It is the algebraic engine the T089
basis-form residual
(`locLift_open_on_image_at_zero_of_basis_form` in
`PresheafTateStructure.lean`) consumes when relating powers of
`locIdeal D₀` to powers of `locIdeal D` modulo a kernel of source-side
operations.

**Strategy (Artin-Rees lemma)**: in a Noetherian ring `R`, given an
ideal `I` and an arbitrary submodule (or ideal) `K`, the filtration
`{I^n ⊓ K}` is `I`-stable: there exists `k₀` such that for all `n ≥
k₀`, `I^n ⊓ K = I^(n-k₀) • (I^k₀ ⊓ K)`. Mathlib provides this directly
via `Ideal.exists_pow_inf_eq_pow_smul` (for any module `M` with
`Module.Finite R M`); for `M = R` (so submodules are ideals), it
yields the classical Artin-Rees statement on intersection of ideal
powers.

The deliverable is the **strongest general theorem** for arbitrary
submodule/ideal `K`, available in three equivalent forms:

* **Submodule form** (`locIdeal_artinRees`) — direct invocation of
  Mathlib's lemma at `R := locSubring P T s`.
* **Ideal form** (`locIdeal_artinRees_ideal`) — translated via
  `Ideal.smul_eq_mul` and `I.mul_top` into the natural ideal-product
  equation `I^n ⊓ K = I^(n-k₀) * (I^k₀ ⊓ K)`.
* **Subset form** (`locIdeal_pow_inter_le_pow_mul`) — the directly
  consumable statement `I^n ⊓ K ≤ I^(n-k₀) * K`, the form that turns
  target-depth membership into a source-depth representative modulo
  the kernel `K`.

**Consumer instantiation (T089 hint)**: Primary's basis-form residual
takes `K := { d : locSubring D₀ | locLift D₀ D h (subtype d) ∈
ker(target embedding) }` (the kernel of the localization-level lift
intersected with the source localization subring). Combined with the
radical relation `D.s^{m_rel} = e · D₀.s` from
`isUnit_algebraMap_s_of_rational_subset`, the Artin-Rees output gives
the source-depth representative for any target-depth element.

**Noetherian hypothesis**: takes `[IsNoetherianRing (locSubring P T
s)]` as an instance argument; this is provided by the existing
`locSubring_isNoetherian` (`Adic spaces/Prop752.lean:146`) when
`[IsNoetherianRing P.A₀]` is available, via Hilbert basis on the
finitely-generated A₀-algebra structure of `locSubring`. -/

omit [IsTopologicalRing A] in
/-- **Strong Artin-Rees theorem for `locIdeal`** (T091 main deliverable,
Submodule form).

For any submodule `K` of `locSubring P T s` (as a self-module), the
`locIdeal`-filtration on `K` is `locIdeal`-stable: there exists `k₀`
such that for all `n ≥ k₀`,

```
(locIdeal P T s)^n • ⊤ ⊓ K = (locIdeal P T s)^(n-k₀) •
  ((locIdeal P T s)^k₀ • ⊤ ⊓ K).
```

Direct application of Mathlib's `Ideal.exists_pow_inf_eq_pow_smul` to
the Noetherian ring `locSubring P T s`. Specialised to the
self-module case, where the submodule `K` plays the role of the
kernel/relevant submodule the consumer cares about.

The `K`-quantifier is **fully general**: any `Submodule (locSubring P T
s) (locSubring P T s)` works, including the kernel-style submodule
shape Primary's basis-form residual consumes. -/
theorem locIdeal_artinRees
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    [IsNoetherianRing (locSubring P T s)]
    (K : Submodule (locSubring P T s) (locSubring P T s)) :
    ∃ k₀ : ℕ, ∀ n : ℕ, k₀ ≤ n →
      (locIdeal P T s) ^ n • (⊤ : Submodule _ _) ⊓ K =
        (locIdeal P T s) ^ (n - k₀) •
          ((locIdeal P T s) ^ k₀ • (⊤ : Submodule _ _) ⊓ K) :=
  Ideal.exists_pow_inf_eq_pow_smul (locIdeal P T s) K

omit [IsTopologicalRing A] in
/-- **Artin-Rees theorem for `locIdeal` in Ideal form** (T091 ticket-
named theorem).

Specialisation of `locIdeal_artinRees` to ideal-multiplication form:
for any ideal `K` of `locSubring P T s`, there exists `k₀` such that
for all `n ≥ k₀`,

```
(locIdeal P T s)^n ⊓ K = (locIdeal P T s)^(n-k₀) * ((locIdeal P T s)^k₀ ⊓ K).
```

**Translation from the Submodule form**: `I^n • ⊤ = I^n * ⊤ = I^n` by
`Ideal.mul_top` (using `I.IsTwoSided`, automatic for `CommRing`); `I •
J = I * J` by `Ideal.smul_eq_mul`. Both rewrites apply cleanly since
`Submodule R R = Ideal R` definitionally.

**Why this is the right form for consumers**: the kernel-filtration
arguments in T089 work with `Ideal (locSubring P T s)` directly (the
kernel of `locLift` restricted to `locSubring D₀` is an ideal). The
Ideal-multiplication form `I^(n-k₀) * (I^k₀ ⊓ K)` is the natural
algebraic shape for further calculation (e.g., reducing modulo the
kernel ideal). -/
theorem locIdeal_artinRees_ideal
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    [IsNoetherianRing (locSubring P T s)]
    (K : Ideal (locSubring P T s)) :
    ∃ k₀ : ℕ, ∀ n : ℕ, k₀ ≤ n →
      (locIdeal P T s) ^ n ⊓ K =
        (locIdeal P T s) ^ (n - k₀) * ((locIdeal P T s) ^ k₀ ⊓ K) := by
  obtain ⟨k₀, hk⟩ := locIdeal_artinRees P T s K
  refine ⟨k₀, fun n hn => ?_⟩
  have h := hk n hn
  rwa [show (locIdeal P T s) ^ n • (⊤ : Submodule _ _) =
        ((locIdeal P T s) ^ n : Ideal _) from by
          rw [Ideal.smul_eq_mul, Ideal.mul_top],
       show (locIdeal P T s) ^ k₀ • (⊤ : Submodule _ _) =
        ((locIdeal P T s) ^ k₀ : Ideal _) from by
          rw [Ideal.smul_eq_mul, Ideal.mul_top],
       Ideal.smul_eq_mul] at h

omit [IsTopologicalRing A] in
/-- **Subset form of Artin-Rees for `locIdeal`** (T091 directly
consumable form).

The most directly useful corollary of `locIdeal_artinRees_ideal` for
kernel-filtration consumers: for any ideal `K` of `locSubring P T s`,
there exists `k₀` such that for all `n ≥ k₀`,

```
(locIdeal P T s)^n ⊓ K ≤ (locIdeal P T s)^(n-k₀) * K.
```

**Mathematical content**: every element of `(locIdeal^n) ⊓ K` (a
target-depth element living in the kernel ideal) admits a
factorisation `∑ i_j * k_j` with `i_j ∈ locIdeal^(n-k₀)` (source-depth
elements) and `k_j ∈ K`. This is precisely the "source-depth
representative modulo kernel" shape consumed by T089's basis-form
residual.

**Use**: combine with the radical relation `D.s^{m_rel} = e · D₀.s` to
turn target-side `locNhd D m` membership of `locLift a` into
source-side `locNhd D₀ n` membership of a representative `b ≡ a (mod
ker(locLift))`. -/
theorem locIdeal_pow_inter_le_pow_mul
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    [IsNoetherianRing (locSubring P T s)]
    (K : Ideal (locSubring P T s)) :
    ∃ k₀ : ℕ, ∀ n : ℕ, k₀ ≤ n →
      (locIdeal P T s) ^ n ⊓ K ≤ (locIdeal P T s) ^ (n - k₀) * K := by
  obtain ⟨k₀, hk⟩ := locIdeal_artinRees_ideal P T s K
  refine ⟨k₀, fun n hn => ?_⟩
  rw [hk n hn]
  exact Ideal.mul_mono_right inf_le_right

omit [IsTopologicalRing A] in
/-- **Containment form: `K ∩ I^n` shrinks past `n - k₀`** (T091
quantitative depth-shifting form).

A pointwise-membership repackaging of `locIdeal_pow_inter_le_pow_mul`:
for any ideal `K`, there exists `k₀` such that for any depth shift `s
: ℕ`, every element of `(locIdeal^(s + k₀)) ⊓ K` lies in `(locIdeal^s)
* K` (i.e., admits a factorisation with one factor of depth `s`).

This phrasing makes the depth-shifting explicit: input depth `s + k₀`,
output depth `s`. Useful when the consumer parameterises by the source
depth `n` (= `s`) and computes the target depth (= `s + k₀`).

**Comparison with `locIdeal_pow_inter_le_pow_mul`**: identical content,
re-indexed to emphasise the shift `(n + k₀) → n`. -/
theorem locIdeal_pow_shift_inter_le_pow_mul
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    [IsNoetherianRing (locSubring P T s)]
    (K : Ideal (locSubring P T s)) :
    ∃ k₀ : ℕ, ∀ n : ℕ,
      (locIdeal P T s) ^ (n + k₀) ⊓ K ≤
        (locIdeal P T s) ^ n * K := by
  obtain ⟨k₀, hk⟩ := locIdeal_pow_inter_le_pow_mul P T s K
  refine ⟨k₀, fun n => ?_⟩
  have hge : k₀ ≤ n + k₀ := Nat.le_add_left k₀ n
  have h := hk (n + k₀) hge
  rwa [show n + k₀ - k₀ = n by omega] at h

omit [IsTopologicalRing A] in
/-- **`locNhd`-image translation of the Artin-Rees subset form** (T091
locNhd-side consumer bridge).

Translates `locIdeal_pow_inter_le_pow_mul` from
`Ideal (locSubring P T s)` form to a `locNhd`-image form on
`Set (Localization.Away s)`: for any ideal `K`, there exists `k₀` such
that for all `n ≥ k₀`, the subtype-image of `(locIdeal^n) ⊓ K` is
contained in the subtype-image of `(locIdeal^(n-k₀)) * K`.

**Mathematical content**: composes `locIdeal_pow_inter_le_pow_mul`
with the subtype-image set-monotonicity, lifting the Artin-Rees
intersection-subset result to a statement about `locNhd P T s n`
intersected with the subtype-image of the kernel ideal `K`.

**Why this form**: the Primary consumer (`locLift_open_on_image_at_zero_of_basis_form`)
operates at the `Localization.Away s` level via `locNhd P T s n`
membership. This `locNhd`-image form is the natural bridge between
the Artin-Rees algebraic decomposition (in `locSubring`) and the
topological filtration (in `Localization.Away s`). -/
theorem locNhd_inter_subtype_image_kernel_le_pow_mul
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    [IsNoetherianRing (locSubring P T s)]
    (K : Ideal (locSubring P T s)) :
    ∃ k₀ : ℕ, ∀ n : ℕ, k₀ ≤ n →
      ((locSubring P T s).subtype ''
          (((locIdeal P T s) ^ n ⊓ K : Ideal _) :
            Set (locSubring P T s)) :
          Set (Localization.Away s)) ⊆
        (locSubring P T s).subtype ''
          (((locIdeal P T s) ^ (n - k₀) * K : Ideal _) :
            Set (locSubring P T s)) := by
  obtain ⟨k₀, hk⟩ := locIdeal_pow_inter_le_pow_mul P T s K
  refine ⟨k₀, fun n hn => ?_⟩
  exact Set.image_mono (hk n hn)

/-! ## Radical-relation / denominator-lifting support (T092)

This section lands the **algebraic engine** for translating between
target and source `locNhd` filtrations through a ring hom that lifts
`algebraMap A`, given the radical relation `e * s_0 = s^N`. Together
with the T091 Artin-Rees package, this is what T089's basis-form
residual (`locLift_open_on_image_at_zero_of_basis_form` consumer in
`PresheafTateStructure.lean`) needs to turn target-depth membership
into a source-depth representative modulo the kernel.

**Setup** (Wedhorn, T089 strategy): the radical relation
`rad_relation_of_rational_subset` produces witnesses
`(N : ℕ, e : A)` with `e * s_0 = s^N` whenever
`rationalOpen D.T D.s ⊆ rationalOpen D₀.T D₀.s` (with `s_0 := D₀.s`,
`s := D.s`). This relation is the algebraic input; the consumer needs
generic localization-side lemmas that turn it into topological
filtration shifts.

**Strategy**: we provide three layers:

* **Generic ring-hom layer** (`map_pow_eq_mul_of_radical_relation`,
  `IsUnit.of_radical_relation`): for any commutative ring `B` and
  ring hom `f : A →+* B`, the relation lifts to `(f s)^N = f e *
  f s_0`. If `f s` is a unit, so is `f s_0` (via `isUnit_of_mul_isUnit`).
  Mathlib-style; reusable in any localization-style or `IsLocalization`
  setup.

* **Localization-side layer** (`algebraMap_eq_pow_mul_divByS_of_radical_relation`):
  in `Localization.Away s_0`, the identity
  `algebraMap A (Localization.Away s_0) e = (algebraMap A
  (Localization.Away s_0) s)^N * divByS 1 s_0` holds. This is the
  source-side reading of the relation, useful for tracking `divByS 1
  s_0` (the inverse of `algebraMap s_0` in `Localization.Away s_0`)
  via `algebraMap` of `e` and `s`.

* **Cross-localization inverse formula**
  (`unit_inv_eq_of_radical_relation`): for any commutative ring `B`
  with `f : A →+* B` and `f s` a unit, the inverse `(f s_0)⁻¹` (which
  exists by the unit transfer) equals `f e * (f s)⁻ᴺ`. This is the
  "denominator-lifting" identity: it expresses the inverse of `f s_0`
  using only `f e` and powers of `(f s)⁻¹`. When applied to `f =
  algebraMap A (Localization.Away s)` (the target localization), this
  gives `(algebraMap s_0)⁻¹ = algebraMap e * (divByS 1 s)^N` in
  `Localization.Away s` — the precise formula Primary's basis-form
  residual exploits to translate target-side `divByS 1 s_0` factors
  into source-side `(divByS 1 s)^N` factors.

**Consumer instantiation** (T089 hint): Primary's basis-form residual
takes `f := algebraMap A (Localization.Away D.s)` and `(s_0, s, e, N)
:= (D₀.s, D.s, e_rad, N_rad)` (from `rad_relation_of_rational_subset`).
The `unit_inv_eq_of_radical_relation` then gives `(algebraMap D₀.s)⁻¹
= algebraMap e_rad * (divByS 1 D.s)^{N_rad}` in `Localization.Away
D.s`. Composing with `IsLocalization.Away.lift D₀.s` (the locLift
construction) yields the target-side formula for `locLift (divByS 1
D₀.s)`. -/

omit [IsTopologicalRing A] in
/-- **Lifted radical relation** (T092 reusable mathlib-style primitive).

For any commutative semiring `S` and ring hom `f : R →+* S`, the
radical relation `e * s_0 = s^N` in `R` lifts under `f` to
`f e * f s_0 = (f s)^N` in `S`. Direct restatement via `map_mul` /
`map_pow`.

**Use**: the algebraic kernel of all subsequent denominator-lifting
identities. Primary instantiates with `f := algebraMap A
(Localization.Away D.s)` (the target-localization map) and obtains
`algebraMap e * algebraMap D₀.s = (algebraMap D.s)^N` in
`Localization.Away D.s`. -/
theorem map_pow_eq_mul_of_radical_relation
    {R S : Type*} [CommSemiring R] [CommSemiring S]
    (f : R →+* S) {s_0 s e : R} {N : ℕ}
    (h_rad : e * s_0 = s ^ N) :
    f e * f s_0 = (f s) ^ N := by
  rw [← map_mul, h_rad, map_pow]

omit [IsTopologicalRing A] in
/-- **Unit transfer via radical relation** (T092 reusable mathlib-style
primitive).

If `e * s_0 = s^N` in a commutative semiring `R`, and `f : R →+* S` is
a ring hom into a commutative semiring `S` with `f s` a unit in `S`,
then `f s_0` is a unit in `S`.

**Mathematical content**: from `f e * f s_0 = (f s)^N` (a unit),
`f s_0` divides a unit, hence is a unit by `isUnit_of_mul_isUnit_right`.

**Use**: Primary's `isUnit_algebraMap_s_of_rational_subset` is the
specialised case `f := algebraMap A (Localization.Away D.s)`, `s_0 :=
D₀.s`, `s := D.s`. This generic form is reusable in any
`IsLocalization`-style or topological lift setup. -/
theorem IsUnit.of_radical_relation
    {R S : Type*} [CommSemiring R] [CommSemiring S]
    (f : R →+* S) {s_0 s e : R} {N : ℕ}
    (h_rad : e * s_0 = s ^ N) (hs : IsUnit (f s)) :
    IsUnit (f s_0) := by
  have heq : f e * f s_0 = (f s) ^ N :=
    map_pow_eq_mul_of_radical_relation f h_rad
  exact isUnit_of_mul_isUnit_right (heq ▸ hs.pow N)

omit [IsTopologicalRing A] in
/-- **`algebraMap s_0 * divByS 1 s_0 = 1`** (T092 reusable primitive —
the basic localization-inverse identity).

In `Localization.Away s_0`, multiplying `algebraMap s_0` by `divByS 1
s_0` yields `1` (since `divByS 1 s_0` is, by definition, the inverse
of `algebraMap s_0`).

**Mathematical content**: direct unfolding of `divByS = mk' Loc 1
⟨s_0, _⟩` and `algebraMap = mk' Loc · ⟨1, _⟩`, then `mk'_mul` and
`mk'_self`.

**Use**: cancellation step in
`algebraMap_eq_pow_mul_divByS_of_radical_relation` and
`algebraMap_mul_pow_divByS_eq_one_of_radical_relation`. -/
theorem algebraMap_mul_divByS_one_eq_one
    {R : Type*} [CommRing R] (s_0 : R) :
    algebraMap R (Localization.Away s_0) s_0 * divByS 1 s_0 = 1 := by
  unfold divByS
  rw [← IsLocalization.mk'_one (M := Submonoid.powers s_0)
        (S := Localization.Away s_0) s_0,
      ← IsLocalization.mk'_mul, mul_one, one_mul]
  exact IsLocalization.mk'_self _ (Submonoid.mem_powers _)

omit [IsTopologicalRing A] in
/-- **Source-side identity from radical relation** (T092 reusable
primitive).

In `Localization.Away s_0`, the radical relation `e * s_0 = s^N`
yields the source-side identity

```
algebraMap A (Localization.Away s_0) e =
  (algebraMap A (Localization.Away s_0) s)^N * divByS 1 s_0.
```

**Mathematical content**: applying `map_pow_eq_mul_of_radical_relation`
at the localization map gives
`(algebraMap s)^N = algebraMap e * algebraMap s_0`. Multiplying both
sides by `divByS 1 s_0` (the inverse of `algebraMap s_0` in
`Localization.Away s_0`) cancels `algebraMap s_0` on the right and
yields the displayed identity.

**Use**: rewrites occurrences of `algebraMap e` (image of the radical
witness `e`) in `Localization.Away s_0` as a product involving
`(algebraMap s)^N` and `divByS 1 s_0`. Source-side companion to
`algebraMap_mul_pow_divByS_eq_one_of_radical_relation` (the target-
side denominator-lifting identity in `Localization.Away s`). -/
theorem algebraMap_eq_pow_mul_divByS_of_radical_relation
    {R : Type*} [CommRing R] {s_0 s e : R} {N : ℕ}
    (h_rad : e * s_0 = s ^ N) :
    algebraMap R (Localization.Away s_0) e =
      (algebraMap R (Localization.Away s_0) s) ^ N * divByS 1 s_0 := by
  have h_pow : (algebraMap R (Localization.Away s_0) s) ^ N =
      algebraMap R (Localization.Away s_0) e *
        algebraMap R (Localization.Away s_0) s_0 :=
    (map_pow_eq_mul_of_radical_relation
      (algebraMap R (Localization.Away s_0)) h_rad).symm
  rw [h_pow, mul_assoc, algebraMap_mul_divByS_one_eq_one, mul_one]

omit [IsTopologicalRing A] in
/-- **Target-side denominator-lifting identity** (T092 strong general
theorem — the key formula Primary's basis-form residual consumes).

In `Localization.Away s`, the radical relation `e * s_0 = s^N` yields

```
algebraMap A (Localization.Away s) s_0 *
  (algebraMap A (Localization.Away s) e * (divByS 1 s)^N) = 1.
```

**Mathematical content**: this identity exhibits `algebraMap e *
(divByS 1 s)^N` as the **inverse** of `algebraMap s_0` in
`Localization.Away s`. Equivalently, it shows that the inverse of
`algebraMap s_0` in target factors through `algebraMap e` and powers
of `divByS 1 s` (the inverse of `algebraMap s` in target). The proof
collapses the product `algebraMap (s_0 * e) * (divByS 1 s)^N` via the
radical relation `s_0 * e = e * s_0 = s^N`, then uses
`algebraMap s * divByS 1 s = 1` (`N`-fold) to finish.

**Use**: this is the precise denominator-lifting identity Primary's
basis-form residual exploits. Combined with the T091 Artin-Rees package
on `K := ker (locLift D₀ D h)` and the source-side identity
`algebraMap_eq_pow_mul_divByS_of_radical_relation`, it lets the
consumer translate a `divByS 1 s_0` factor (in source) into a
`(divByS 1 s)^N` factor (in target via `algebraMap e`), shifting
filtration depth between `locNhd D₀ n` and `locNhd D m`.

**Consumer instantiation hint**: applied to `s_0 := D₀.s`, `s := D.s`,
`(e, N) := (e_rad, N_rad)` from
`rad_relation_of_rational_subset D₀ D h`, this gives the inverse of
`algebraMap A (Localization.Away D.s) D₀.s` (which is the unit
witness `isUnit_algebraMap_s_of_rational_subset`) explicitly as
`algebraMap e_rad * (divByS 1 D.s)^{N_rad}`. -/
theorem algebraMap_mul_pow_divByS_eq_one_of_radical_relation
    {R : Type*} [CommRing R] {s_0 s e : R} {N : ℕ}
    (h_rad : e * s_0 = s ^ N) :
    algebraMap R (Localization.Away s) s_0 *
        (algebraMap R (Localization.Away s) e * (divByS 1 s) ^ N) = 1 := by
  -- Pull the e and s_0 algebraMap factors together: algebraMap (s_0 * e) = algebraMap (s^N)
  have h_pow : algebraMap R (Localization.Away s) s_0 *
      algebraMap R (Localization.Away s) e =
      (algebraMap R (Localization.Away s) s) ^ N := by
    rw [mul_comm]
    exact map_pow_eq_mul_of_radical_relation
      (algebraMap R (Localization.Away s)) h_rad
  -- algebraMap s * divByS 1 s = 1 in Loc s
  have h_inv : algebraMap R (Localization.Away s) s * divByS 1 s = 1 :=
    algebraMap_mul_divByS_one_eq_one s
  -- Combine: (algebraMap s_0 * algebraMap e) * (divByS 1 s)^N
  --        = (algebraMap s)^N * (divByS 1 s)^N
  --        = (algebraMap s * divByS 1 s)^N = 1^N = 1
  calc algebraMap R (Localization.Away s) s_0 *
        (algebraMap R (Localization.Away s) e * (divByS 1 s) ^ N)
      = (algebraMap R (Localization.Away s) s_0 *
          algebraMap R (Localization.Away s) e) * (divByS 1 s) ^ N := by
        rw [mul_assoc]
    _ = (algebraMap R (Localization.Away s) s) ^ N * (divByS 1 s) ^ N := by
        rw [h_pow]
    _ = (algebraMap R (Localization.Away s) s * divByS 1 s) ^ N := by
        rw [mul_pow]
    _ = 1 ^ N := by rw [h_inv]
    _ = 1 := one_pow N

end ValuationSpectrum
