import «Adic spaces».Basic

/-!
# Nonarchimedean Scottish Book — Problem 33

**Proposer:** Kiran Kedlaya
**Date:** 7 July 2020

## Problem Statement

Let (R, R+) be a perfectoid Huber pair in characteristic p. Equip W(R+) with the
(p, [x])-adic topology for a topologically nilpotent unit x in R. Is W(R+) sheafy?

## Notes

None.

## Status

Open.

## Definitions needed

- **Witt vectors W(R+)**: The ring of p-typical Witt vectors of R+.
- **(p, [x])-topology**: The topology on W(R+) defined by the ideal generated by p and
  the Teichmuller lift [x] of a topologically nilpotent unit x ∈ R.
- **Perfectoid**: A Huber pair satisfying the perfectoid condition in characteristic p.
-/
